### ISSUE TITLE
Wrong order in sorting grouped files

### ISSUE THREAD

**Issue by kapitanluffy** [derceg/explorerplusplus#101]
![image](https://user-images.githubusercontent.com/485799/36607060-78126b52-1900-11e8-9601-8caba3120eaa.png)

Files are grouped by "Date Created" and ordered by "Date Created" descending.

Windows explorer looks like this
![image](https://user-images.githubusercontent.com/485799/36607159-c6178cd8-1900-11e8-8089-9240172ef2f4.png)

**Comment by derceg** [comment]
Currently, all groups are sorted by name. To fix this issue, some groups should be sorted by their content instead.
