### ISSUE TITLE
Not working in Windows XP

### ISSUE THREAD

**Issue by Tallefer** [derceg/explorerplusplus#107]
Since build [1.4.0.122](https://ci.appveyor.com/project/derceg/explorerplusplus/build/1.4.0.122) ([Remove unused constant](https://github.com/derceg/explorerplusplus/commit/aba26f5769a4d90c92cbd6d0c6d854665386715b)) Explorer++ is no longer working in XP, minimum system version was changed from 5.1 to 6. In later builds there are even new imports from dlls absent in XP.
Last working build is [1.4.0.121](https://ci.appveyor.com/project/derceg/explorerplusplus/build/1.4.0.121)
Because there was no explicit info anywhere about "end of support" or similar thing, this problem came as a nasty surprise.
Please consider maintaining XP compatibility, for this is too useful a software to lose.
Thank you.

**Comment by derceg** [comment]
I understand the concern, but removing support for XP was a conscious decision. My reasoning is outlined in 502d7a28cb287c0e28cff845c312d8fd00261b96. Aside from the items listed there, I also based the decision on the following:

- Microsoft ended support for Windows XP 4 years ago.
- The market share for Windows XP is at a few percent globally.
- Over the last 3 months, about 1.5% of the people visiting https://explorerplusplus.com were using Windows XP.

Generally speaking, keeping support for XP has a cost and dropping it makes it easier to use functionality only present in newer versions of Windows. Vista will probably also be dropped at some point, though not just yet.

Once the next version is actually released, the site will be updated to indicate that XP is no longer supported. In the meantime, I might also update https://explorerplusplus.com/changelog, based on the current contents of the History.txt file, as this change is mentioned [there](https://github.com/derceg/explorerplusplus/blob/a27e9c1828c8a418376689bd60d5b759bc6cc547/Documentation/User/History.txt#L35).

**Comment by Tallefer** [comment]
Well, this is sad, as always in such cases… Could you please at least backport all the major bugfixes before dropping XP support completely? Because, as usual, such things as MS support, market share and other "corporate-important" stats mean little to nothing to end-users who are enjoying this software for many years already, and, quite commonly, aren't able to upgrade their systems or hardware (and, obviously, guest systems when using portable mode) due to various reasons. It is a very common discussion nowadays, sadly…

**Comment by derceg** [comment]
> Could you please at least backport all the major bugfixes before dropping XP support completely?

Perhaps, if it's simple to do, but I can't guarantee anything.

**Comment by Beep6581** [comment]
Your reasons for dropping support for XP sound valid and being in your position I may have done the same if I felt the full extent of the problems. However, I wanted to point out that:
1. XP is very much in use in third-world countries.
2. The percentage of people visiting your site identified as using XP is an unreliable metric for establishing how many XP users use E++. I visit your site from Chromium/Linux and from whatever my smartphone runs, while I want to use E++ in a 32-bit XP which I run in VirtualBox.

It would be nice if there was one final XP build which automatically refreshed the contents of the current dir, as I find that if I'm on a mapped network drive or a UNC location (specifically, a "shared folder" in VirtualBox), then whatever changes I make in that folder (e.g. delete a file) are not reflected until I manually re-enter it or manually hit F5.

**Comment by derceg** [comment]
It's understandable some people might still be using XP, but I won't be creating any more builds for it. So if someone does want builds that work on XP, the best idea would be to create a fork.
