### ISSUE TITLE
"Load previous tabs" not always honored

### ISSUE THREAD

**Issue by chuim** [derceg/explorerplusplus#111]
I've been using Explorer++ for a few weeks and it seems that in a couple situations I didn't get tabs from the previous session restored as they should. This seemed to happen when it was unable to properly "close": in a hard reset situation and even when requesting Windows to shut down without closing Explorer++ first. What I did get was tabs from a previous time I got to actually close Explorer++ properly.

**Comment by derceg** [comment]
Since Explorer++ now saves settings every 30 seconds, this should at least be mitigated.
