### ISSUE TITLE
(null) is not a valid Win32 application

### ISSUE THREAD

**Issue by Beep6581** [derceg/explorerplusplus#112]
When I run `Explorer++.exe` from https://ci.appveyor.com/api/projects/derceg/explorerplusplus/artifacts/explorer++_x86.zip?branch=master&job=Platform%3A%20Win32 from 2018-04-18 in Windows XP 32-bit I get:
![imgur-2018_04_18-10 03 16](https://user-images.githubusercontent.com/5844619/38919053-c9ede65e-42ef-11e8-91d5-d93469a60860.png)

This version runs fine:
https://explorerplusplus.com/software/explorer++_1.3.5_x86.zip

**Comment by Tallefer** [comment]
Please look at this issue: https://github.com/derceg/explorerplusplus/issues/107
And add your voice :)

**Comment by Beep6581** [comment]
Closing as duplicate of #107
