### ISSUE TITLE
Cannot edit a new file or folder

### ISSUE THREAD

**Issue by ernstblaauw** [derceg/explorerplusplus#113]
If I create a new file or folder, it shows the wrong item (namely an empty sheet). 
And before I can edit or open the file or folder, I have to press F5; otherwise, F2 or double-click won't trigger an action.
I'm running W10 build 1703, 64-bit.

**Comment by derceg** [comment]
I don't think I've encountered this, so I'll assume whatever was causing it is fixed. If its still happens in the latest builds, feel free to repoen.
