### ISSUE TITLE
Open bookmarks from "Organize Bookmarks" with keyboard

### ISSUE THREAD

**Issue by MarkusAmshove** [derceg/explorerplusplus#117]
Hi,

I'm currently looking for a replacement for another explorer software I use and it is mandatory for me to use it completely with keyboard.

I'm very impressed with Explorer++ capabilities to support this, but one thing I found strange is that I can't open bookmarks in the "Organize Bookmarks" view by simply pressing enter.
I've seen in the docs that I can right click and select open, but I also can't use the "right click" buttom of my keyboard to open the context menu.

I'm not experienced enough in C++ to make the change myself and submit a PR, but maybe you'll be able to support this in the future :-)

A similar thing that bugged me (a bit) was that I'm not able to quickly navigate back into the explorer view. If I press CTRL+L to get to the address bar and then either navigate somewhere (or not) I expected to get back to the actual explorer by pressing ESC. Just a small nitpick from me :-)

Otherwise, great software! Keep up the good work

**Comment by derceg** [comment]
The items brought up here have all been implemented:

- Pressing enter on a bookmark in the manage bookmarks dialog will open that bookmark in a new tab.
- Pressing the context menu key on a bookmark in the manage bookmarks dialog will show the context menu for that bookmark.
- Pressing escape while the address bar has focus will switch the focus back to the active file list.
