### ISSUE TITLE
Very slow to select multiple files by using Ctrl or Shift key

### ISSUE THREAD

**Issue by AndyZhang001** [derceg/explorerplusplus#120]
Great tool. Good job. I just start to use it and got below problem.
It is very slow in below cases：
1. select a range of files by using shift key, then hold shift key and click on another file. 
2. select more than one files by using ctrl key.
Also is there a way to close the feature that rename of by click a file twice?

**Comment by AndyZhang001** [comment]
Please ignore it. Seems it is the issue of windows explorer. Some shell extensions cause the issue.

**Comment by derceg** [comment]
Just in case anybody else has a similar question: no, there's no way to disable the click to rename feature.
