### ISSUE TITLE
KB should be kB

### ISSUE THREAD

**Issue by HarmOtten** [derceg/explorerplusplus#122]
When looking at the unit of the size of files, k(ilo) should be typed in lower case.
So "KB" should be "kB".
See also: https://en.wikipedia.org/wiki/Metric_prefix
Just a minor issue, but I think easy to correct.

**Comment by marcosfrm** [comment]
KB is "correct":

https://en.wikipedia.org/wiki/JEDEC_memory_standards#Unit_prefixes_for_semiconductor_storage_capacity

To be really correct:

https://en.wikipedia.org/wiki/Binary_prefix
