### ISSUE TITLE
Closing the "Downloads" tab halts the program. Not 100% reproducible.

### ISSUE THREAD

**Issue by erikjuvan** [derceg/explorerplusplus#124]
On 64 bit Windows 10 built with Visual Studio 15.8.8 (msvc 19.15.26732.1) on all combinations of Release/Debug and 32/64 bit.

Closing the "Downloads" tab and mostly only the "Downloads" tab halts the program (most of the times, but not always - not 100% reproducible) at 
iFolderView.cpp:170 "WaitForSingleObject(m_hIconEvent,INFINITE);"

If by some chance the system doesn't halt it crashes right after with a memory dereference violation.

My wild guess is it may have something to do with the thumbnail.

**Comment by derceg** [comment]
I think this is probably fixed by the linked commit, but feel free to add a comment here if not.
