### ISSUE TITLE
Missing Network Drive

### ISSUE THREAD

**Issue by blimeybloke** [derceg/explorerplusplus#129]
I am on Win10, have tried to run as Admin and regular user.

When I open Explorer++ it does not list my network drives, nor does it let me connect even if I try F: for example.  I have verified in windows explorer the drive is there and I am able to connect to it.
I am hoping this is a setting somewhere.

Thank you

**Comment by derceg** [comment]
Off the top of my head, I'm not sure what would cause that. I have a network drive set up and it appears correctly within Explorer++.

Does the drive show up in the treeview on the left?

**Comment by derceg** [comment]
I'm going to close this, as I don't think I've seen this issue before and without being able to reproduce it, there's not much I can do.

**Comment by blimeybloke** [comment]
Yea, still having issue as I just tried again today.
