### ISSUE TITLE
Extracting from zip does not appear to work

### ISSUE THREAD

**Issue by Tricky1975** [derceg/explorerplusplus#144]
Reading the zip content works... That is, showing the files inside the zip, but when it comes to actually unzipping them. I tried dragging them to my target folder (nothing happened), and I tried copy-and-paste, and all I got was a text file containing an old string I copied an pasted before, but not the zipped files.

(Opening cmd, using 'cd' to go to my target folder then typing "unzip" and dragging the zip-file to the command prompt, that did work, but that's a bit awkward) :P

**Comment by jczanfona** [comment]
Me too.
The content of a zip file (opened in Explorer ++) cannot be copied to another folder, it does nothing. Either one file or all of them.

But the 'Copy to folder' menu option does.
