### ISSUE TITLE
[1.4.0.789] Date format using "Yesterday" and "Today" 

### ISSUE THREAD

**Issue by GHL1** [derceg/explorerplusplus#146]
System: Windows 10 Pro
Explorer Version: 1.4.0.789
Behavior: Reproducable
Priority: Major
Language: German; but also seen in English localization

Date format is including "Yesterday" and "Today", even in German localization.

Expected behavior:

Date format shall always be - in German localization - dd.mm.YYYY hh:mm:ss.

See attached schreenshot:
![grafik](https://user-images.githubusercontent.com/49457452/55833073-40bcc800-5b17-11e9-8d25-a7d50c15279c.png)

**Comment by derceg** [comment]
If you uncheck Tools > Options > Files and Folders > Show user friendly dates, dates should be formatted using your locale.
