### ISSUE TITLE
[1.4.0.789] Toolbar icon for Command Shell (cmd) not functional

### ISSUE THREAD

**Issue by GHL1** [derceg/explorerplusplus#147]
System: Windows 10 Pro
Explorer Version: 1.4.0.789
Behavior: Reproducable
Priority: Major
Language: German, but also observed in English localization

When clicking on the toolbar icon for invoking the Command Shell (cmd) nothing happens.
It is currently only a symbol without any  function.

Expected bahavior:

Icon is clicked and Command Shell (cmd) opens.

See attached screenshot:

![grafik](https://user-images.githubusercontent.com/49457452/55833859-cf7e1480-5b18-11e9-9760-be776fed08d0.png)
nguage: German; but also seen in English localization

**Comment by derceg** [comment]
Clicking the button essentially just executes C:\WINDOWS\system32\cmd.exe. Can you test with the latest version to see if this is still a problem?
