### ISSUE TITLE
[1.4.0.xxx] Latest compiled build on Github opens with DLL language mismatch message

### ISSUE THREAD

**Issue by GHL1** [derceg/explorerplusplus#148]
System: Windows 10 Pro
Explorer Version: 1.4.0.xxx
Behavior: Reproducable
Priority: Minor
Language: German

When downloading from Github https://github.com/derceg/explorerplusplus latest build of Explorer++ and the German language pack the Explorer++ opens with a message box warning that the file/version of the language pack is not matching file/version number of the Exlplorer++.

As a result the language is not changed and stays English.

As a workaround for myself I edited file and version information of the DLL on my local PC with rcedit to 1.4.0.876 and then Explorer++ used the language pack properly.

However version and file information of Explorer++ and language packs shall be alignd when compiling new builds.

Other finding:

The information in this warning box is not written in proper German and runs "Die Version des angegebenen DLL Übersetzung stimmt nicht mit der Version der ausführbaren Datei".

This text should read in proper German: "Die Version der Sprach-DLL ist mit der aktuellen Version des Explorer++ nicht kompatibel !"

I will try to find the string on https://crowdin.com/translate/explorerplusplus/7/en-de#q=version and change it accordingly.

See attached screenshot:

![grafik](https://user-images.githubusercontent.com/49457452/55835995-8aa8ac80-5b1d-11e9-9892-66f3841dfa58.png)

**Comment by derceg** [comment]
With some recent changes (specifically 1ca6b6edd79116679f845dd18f83a8713fa012e5), this issue should be fixed.
