### ISSUE TITLE
[1.4.0.789] Date format used is hh:mm instead of formerly hh:mm:ss

### ISSUE THREAD

**Issue by GHL1** [derceg/explorerplusplus#149]
System: [Windows 10 Pro]
Explorer Version: 1.4.0.789
Behavior: Reproducable
Priority: Major
Language: any

Unfortunately you decided to display the date on Explorer++ in line with Microsoft, which removed the seconds.

I'd immensely appreciate if you could revoke your decision and use hh:mm:ss again, as this is only one reason, why I do not like Microsofts file explorer !

It could make a big difference to have seconds displayed as part of the file name in a file explorer.

I'd also be curious to learn the opinion of other users.

Expected behavior:

Please bring back seconds in the timestamps used in Explorer++ !!!

See attached screenshot:

![grafik](https://user-images.githubusercontent.com/49457452/55836362-9648a300-5b1e-11e9-9769-885e3b25b439.png)

**Comment by InkleDot** [comment]
Using Ver 1.4.0.1205 64bit unicode on Windows 7 Pro.

I'd like to second the motion to bring back seconds on timestamps.
Have been using Explorer++ for many years, it's a great program and seconds are really useful in determining which file is actually the latest etc.

Ver 1.3.5.appears to use Windows Long Time, ver 1.4 looks to be using Short Time. Unfortunately even though one can configure Short Time to be HH:mm:ss, only Long Time will actually display seconds (as it says on Customize Format).
So, it would be good if we could we just have seconds back as the default.
