### ISSUE TITLE
Bookmarks randomly reorganize

### ISSUE THREAD

**Issue by petbadger** [derceg/explorerplusplus#151]
Great software! I use the bookmarks feature often. Oddly, the bookmarks never seem to stay in the same order. Whenever I close and restart the software, the order will be different.   I just tested it 6 times and the ordering was different each time. 

I also explicitly organized each bookmark by moving it up and down.  It still doesn't retain the ordering.

Version 1.3.5.531 64bit

I downloaded and ran 1.4.0.796 and now my bookmarks have been erased completely.  Not a big deal, but thought you might like to know.

**Comment by esyriani** [comment]
Yes, I have the same issue. Do you recommend I move to v1.4 (beta)? I extensively use bookmarks, but they keep changing position. I am under Windows 10. Thanks.

**Comment by derceg** [comment]
Bookmarks should retain their order in version 1.3.5, so I'm not sure why that's happening. The bookmarks system was rewritten for version 1.4, so any bookmark bugs that are specific to 1.3.5 aren't going to be fixed, unfortunately.

As for whether to move to 1.4 beta, I'd generally recommend doing that. Especially if you use the bookmarks functionality regularly; it would be good to get feedback on whether anything is broken before the stable version is released ;)
