### ISSUE TITLE
Cannot run Explorer++

### ISSUE THREAD

**Issue by CanuckGamer** [derceg/explorerplusplus#152]
I've downloaded the 64 bit binary build from today (15 May 2019) and yesterday. Neither will run. I double click Explorer++.exe and the program never appears on my taskbar (Windows 10), and I don't see any process for Explorer++ in Task Manager.

An older build (v1.4.0.796 from 22 April 2019) runs with no issues on my machine.

**Comment by CanuckGamer** [comment]
Still having the same issue with the 64-bit download today. As mentioned, I run the 64-bit version of the older v1.4.0.796.

**Comment by CanuckGamer** [comment]
I looked in the Windows event viewer, there is an "Application Error". The general tab shows:

Faulting application name: Explorer++.exe, version: 1.4.0.801, time stamp: 0x5cd2ecd9
Faulting module name: Explorer++.exe, version: 1.4.0.801, time stamp: 0x5cd2ecd9
Exception code: 0xc000041d
Fault offset: 0x00000000001d2e60
Faulting process id: 0x5b0
Faulting application start time: 0x01d51168b795dd87
Faulting application path: N:\shared\cameron\explorer++_x64\Explorer++.exe
Faulting module path: N:\shared\cameron\explorer++_x64\Explorer++.exe
Report Id: 67616750-fd7d-4634-9c3b-c6b059387603
Faulting package full name: 
Faulting package-relative application ID:

**Comment by CanuckGamer** [comment]
Just downloaded the latest build. I see this in the windows (10) event viewer:

Faulting application name: Explorer++.exe, version: 1.4.0.831, time stamp: 0x5d21246b
Faulting module name: KERNELBASE.dll, version: 10.0.17763.615, time stamp: 0xb6cb145b
Exception code: 0xc000041d
Fault offset: 0x0000000000039129
Faulting process id: 0x38e4
Faulting application start time: 0x01d53b0d08b475f6
Faulting application path: C:\Users\aparker\Downloads\explorer++_x64 (5)\Explorer++.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3e58b9ca-315f-4c07-a49a-522454662e0b
Faulting package full name: 
Faulting package-relative application ID: 


The XML view in the event viewer shows:

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Application Error" /> 
		<EventID Qualifiers="0">1000</EventID> 
		<Level>2</Level> 
		<Task>100</Task> 
		<Keywords>0x80000000000000</Keywords> 
		<TimeCreated SystemTime="2019-07-15T12:58:46.117753900Z" /> 
		<EventRecordID>141314</EventRecordID> 
		<Channel>Application</Channel> 
		<Computer>REMOVED_FOR_SECURITY_PURPOSES</Computer> 
		<Security /> 
	</System>
	<EventData>
		<Data>Explorer++.exe</Data> 
		<Data>1.4.0.831</Data> 
		<Data>5d21246b</Data> 
		<Data>KERNELBASE.dll</Data> 
		<Data>10.0.17763.615</Data> 
		<Data>b6cb145b</Data> 
		<Data>c000041d</Data> 
		<Data>0000000000039129</Data> 
		<Data>38e4</Data> 
		<Data>01d53b0d08b475f6</Data> 
		<Data>C:\Users\aparker\Downloads\explorer++_x64 (5)\Explorer++.exe</Data> 
		<Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
		<Data>3e58b9ca-315f-4c07-a49a-522454662e0b</Data> 
		<Data /> 
		<Data /> 
	</EventData>
</Event>

**Comment by endo64** [comment]
It looks your virus protection / Windows Defender removes the application,
Check the downloaded file on virustotal.com if it is safe, exclude it from defender or temporarily disable your AV to test if it works.

**Comment by CanuckGamer** [comment]
The "REMOVED_FOR_SECURITY_PURPOSES" line? Hrm, even with Defender off (my only anti viri) I still have the issue. Older versions still work <sighs> I'll look into this.

**Comment by CanuckGamer** [comment]
Why do you say that? "REMOVED_FOR_SECURITY_PURPOSES" doesn't actually appear in the event viewer. I manually put that there as it was the computer name field which contains sensitive domain information.

**Comment by endo64** [comment]
Ah, sorry I wasn't careful enough.
Still it's a good idea to temporarily disable AV and test. I remember Explorer++ has some issues on Win10 before, but I'm using it over a year without any issue.

**Comment by CanuckGamer** [comment]
I discovered the problem. SmartScreen is blocking Explorer++ from running. SmartScreen gave no warnings or prompts, it just blocked Explorer++. Further, it doesn't seem to write anything useful into the Windows Event log. With SmartScreen disabled I can run Explorer++ without any issue.

**Comment by endo64** [comment]
You can close the issue then, thanks for the solution.

**Comment by CanuckGamer** [comment]
SmartScreen causes the issue. Turning off SmartScreen (which is not ideal), fixes the problem.
