### ISSUE TITLE
Keyboard shortcuts customization

### ISSUE THREAD

**Issue by zalmanlew** [derceg/explorerplusplus#153]
I want to be able to easily **Destroy Files**.

Currently, I have to click ** Actions → Destroy File(s)...** and then do it.

I was wondering if there was a way to assign it a keyboard shortcut.

Also, it'd be nice if it had it's own button on top which could be enabled/disabled.

**Comment by derceg** [comment]
There is in the latest development build.

Follow the steps shown in [Plugins/Readme.txt](https://github.com/derceg/explorerplusplus/blob/554ecc2f797350455afce54bdd5156912cf0f81a/Plugins/Readme.txt) to run Explorer++ with plugin support. In this case, you'd want to copy the [update_accelerators](https://github.com/derceg/explorerplusplus/tree/554ecc2f797350455afce54bdd5156912cf0f81a/Plugins/update_accelerators) folder into the plugins directory. You could then update [plugin.json](https://github.com/derceg/explorerplusplus/blob/554ecc2f797350455afce54bdd5156912cf0f81a/Plugins/update_accelerators/plugin.json) to add whatever keyboard shortcuts you like for the main menu items. You can find a list of the available menu items in [AcceleratorMappings.h](https://github.com/derceg/explorerplusplus/blob/554ecc2f797350455afce54bdd5156912cf0f81a/Explorer%2B%2B/Explorer%2B%2B/AcceleratorMappings.h).

If you want to add a shortcut key for the destroy files menu item, you'd add something like the following json:

```json
"shortcut_keys": [
  {
    "command": "destroy_files",
    "keys": [
      "Alt+Shift+D"
    ]
  }
]
```

This functionality was only added very recently, so there's no documentation just yet.

**Comment by WELZ-gh** [comment]
@derceg that's awesome, thanks a lot!

Is there any documentation or list on what string corresponds to which key and how I need to write them? I tried adding using `Ctrl` and `Control` and that didn't work.

**Comment by derceg** [comment]
This work is now tracked in #476. There's some tasks I've added there about documentation for the plugins functionality.
