### ISSUE TITLE
Bug: dragging folders to bookmarks toolbar doesn't really put a shortcut to them

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [derceg/explorerplusplus#156]
See attached video (v1.4.0.831) :

[2019-07-24_22-58-53.zip](https://github.com/derceg/explorerplusplus/files/3428559/2019-07-24_22-58-53.zip)

It can even crash, as you see...

**Comment by derceg** [comment]
The bookmarks functionality wasn't completely implemented in 1.4.0 until relatively recently, so this should be fixed now. Feel free to add a comment here if you're still seeing an issue.
