### ISSUE TITLE
Bug: SVG and WEBP not viewed, even though I've installed plugins for Explorer that shows them

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [derceg/explorerplusplus#159]
Try the attached files in thumbnails view:

[test.zip](https://github.com/derceg/explorerplusplus/files/3428582/test.zip)

**Comment by kettenfett** [comment]
I also would like for Explorer++ to create thumbnails for webp images. I have 1.4.0.1637, and it's not doing that.
