### ISSUE TITLE
Bookmarks disappear between program uses

### ISSUE THREAD

**Issue by Avrution** [derceg/explorerplusplus#162]
I will bookmark items and they work fine, but when the program is closed and reopened all bookmarks disappear.

This is in 1.4.0.796

**Comment by BaesFr** [comment]
Still in 1.4.0.1142

**Comment by brunocicom** [comment]
Still in 1.4.0.1172

**Comment by FinalFrontierPrototyping** [comment]
Still in 1.4.01205

**Comment by brunocicom** [comment]
fixed in 1.4.0.1265

**Comment by derceg** [comment]
As mentioned above, this should be fixed now.
