### ISSUE TITLE
renaming a file or directory: active tab closes instead of renaming

### ISSUE THREAD

**Issue by telebiker** [derceg/explorerplusplus#165]
Submitting a bug as reported by JMN user in the [forum](https://explorerplusplus.com/forum/viewtopic.php?f=5&t=2309):

> right-click on the file or directory entry, choose rename. When I push any letter key or <Delete> or <Backspace> the application crashes. If there are multiple tabs open, only the active tab closes. A directory can be successfully rename using the tree pane. I first saw this behavior in build 1.4.0.831. It happens in both the x86 and x64 versions of the app. I am using Windows 10 x64. A DMP file is attached.

[Explorer++1.4.0.831-26072019-104150.dmp.zip](https://github.com/derceg/explorerplusplus/files/3684661/Explorer%2B%2B1.4.0.831-26072019-104150.dmp.zip)

I have the same behaviour in my Win 10 x64.

I can add that I was able to reproduce this on 1.4.0.825 as well. But not on 1.4.0.801.

This is pretty annoying bug since renaming is one of the most often features of the file manager.

**Comment by telebiker** [comment]
I believe this was introduced somewhere here: https://github.com/derceg/explorerplusplus/commit/a22d53f491815d6d359fe5853f60a3be19df9881

I can see something related renaming but not sure where exactly a root cause is.

**Comment by CanuckGamer** [comment]
With the latest build renaming a file or directory causes the tab to exit if there are multiple tabs open, but the app doesn't crash. I've not yet tested to see what happens when you've only one tab open.

Version: 1.4.0.831

**Comment by telebiker** [comment]
>  If there are multiple tabs open, only the active tab closes. 

> With the latest build renaming a file or directory causes the tab to exit if there are multiple tabs open

No contradiction

**Comment by CanuckGamer** [comment]
Developers can't fix bugs when you mean "one tab closes" but what you say is, the process exists and its PID no longer exists.

Those are NOT the same things to a developer. To get bugs fixed you have to accurately and precisely describe the problem.

**Comment by CanuckGamer** [comment]
> > If there are multiple tabs open, only the active tab closes.
> 
> > With the latest build renaming a file or directory causes the tab to exit if there are multiple tabs open
> 
> No contradiction. Closing active tab instead of renaming brings the same level of frustration as crashing the app instead of renaming while one tab is active.

Developers can't fix bugs when you mean "one tab closes" but what you say is, "the process exits and its PID no longer exists."

Those are NOT the same things to a developer. To get bugs fixed you have to accurately and precisely describe the problem.

**Comment by telebiker** [comment]
Oh. I thought that this bug was closed, but it was not. I will delete another duplicated bug I've created. Sorry for that. I will provide more clarification on the next comment.

**Comment by telebiker** [comment]
I really like explorer++ file manager, and there is something wrong with renaming process. If the bug was not properly issued, I'm sorry for that. I would be glad to provide more information, but I'm not sure what else can I do.

The story:

JMN user reported in the [forum](https://explorerplusplus.com/forum/viewtopic.php?f=5&t=2309) the following behaviour:

> right-click on the file or directory entry, choose rename. When I push any letter key or <Delete> or <Backspace> the application crashes. If there are multiple tabs open, only the active tab closes. A directory can be successfully rename using the tree pane. I first saw this behavior in build 1.4.0.831. It happens in both the x86 and x64 versions of the app. I am using Windows 10 x64. A DMP file is attached.

[Explorer++1.4.0.831-26072019-104150.dmp.zip](https://github.com/derceg/explorerplusplus/files/3684661/Explorer%2B%2B1.4.0.831-26072019-104150.dmp.zip)

I'm not JMN user from the forum, I'm another person. All I know regarding JMN user's issue is what I have quoted here. The links to the original forum thread and his/her dump are attached to this bug. 

But JMN user had this experience:
> If there are multiple tabs open, only the active tab closes.

@CanuckGamer had this:
> With the latest build renaming a file or directory causes the tab to exit if there are multiple tabs open

I've sent a message on the forum to JMN user, probably, he/she could give some more details. Probably something useful is in his/her dump.

The reason I've opened this bug is because I was not able to find any open bug regarding renaming process. That forum thread was the only thing that I found. I'm not sure if bug reports on the forum are tracked somehow.

**Comment by telebiker** [comment]
While trying to reproduce the bug, I had similar to @CanuckGamer results. When I was trying to rename a file or a directory and I had multiple tabs opened, the active tab closed.

I have verified multiple Explorer++ versions on Win 10 x64: I was able to reproduce the bug on  1.4.0.831 and 1.4.0.825 as well. But not on 1.4.0.801 or any earlier versions.

Because of that, I suppose that it was introduced here: https://github.com/derceg/explorerplusplus/commit/a22d53f491815d6d359fe5853f60a3be19df9881. This commit has some changes regarding renaming process.

Please let me know what in case some clarification is required. Thank you.

**Comment by daniel-sch** [comment]
This seems to be fixed in version 1.4.0.915 (from yesterday).

**Comment by telebiker** [comment]
ooops, seems that original bug was #163

**Comment by telebiker** [comment]
Can confirm that fixed in 1.4.0.915.

Awesome news. It's cool that such a great file manager is still alive.
