### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by alabotski** [derceg/explorerplusplus#177]
When I specify in the settings, work in - portable mode
Explorer ++ no longer starts

1.4.0.1026

**Comment by WildByDesign** [comment]
@alabotski  This is likely related to the following bug:
[https://github.com/derceg/explorerplusplus/issues/83](url)

I have a temporary work-around that is working but only temporary solution.
[https://github.com/derceg/explorerplusplus/issues/83#issuecomment-479501544](url)

Deeper analysis on where bug started and potential code fix suggestion:
[https://github.com/derceg/explorerplusplus/issues/83#issuecomment-479590300](url)

From my own further testing, in portable, this issue causes crashes and is unable to customize the toolbar.

In non-portable mode, it does not seem to cause crashes but user is still unable to customize the toolbar.

@derceg  Would you be able to have a look at this issue regarding customization of toolbar broken which also is causing crashing upon app start in Portable mode?  Thank you.
