### ISSUE TITLE
Right clicking in empty spot in window when looking at drive or folder contents crashes the app.

### ISSUE THREAD

**Issue by donnyv** [derceg/explorerplusplus#178]
When I right click anywhere in an empty spot in the window. Whether its a drive or folder. The app hangs and then crashes. This also happened a couple times right clicking tabs multiple times in a row. Also the details view didn't hold after I set it globally.

Using version 1.3.5 on Windows Enterprise 10.0.16299 Build 16299
Processor: Intel(R) Xeon(R) CPU E5-1607 0 @ 3.00GHz, 3000 Mhz, 4 Core(s), 4 Logical Processor(s)
Ram: 16GB

**Comment by sean-e** [comment]
No repro in 1.4.0.1596 or master as of today.  You should running a more recent build.  See Latest Builds at https://github.com/derceg/explorerplusplus#latest-builds

**Comment by derceg** [comment]
I can't reproduce either in the latest version. Feel free to add a comment here if this is still a problem in 1.4.x.
