### ISSUE TITLE
Latest 1.4 develepoment version cannot display anything in Windows 10 

### ISSUE THREAD

**Issue by yuanhuanglin** [derceg/explorerplusplus#189]
Hi

I download the Explorer++ Development Build 64-bit and also using the lastest GitHub source to build explorer++ 64 bit, but when I double click the explorer++.exe to run, what I can only see is the desktop having a refresh ( at the taskbar) and nothing appeared.  I can confirm the explorer++.exe process in the windows task manager and can only close the explorer++ by killing the process.

Does anybody have the same issue?

OS: Windows 10 2019 Nov. Updated
APP: Explorer++ 64bit, 1.4.x?

Thanks!

Aaron

**Comment by jczanfona** [comment]
Not me.
Using E++ v.1.4.0.1588 with W10 1909 64 bits

**Comment by derceg** [comment]
There was an issue that was fixed shortly before the 1.4.0 beta was released that could cause the application to crash at unexpected times. Could you try again with the beta and see if that works?

**Comment by derceg** [comment]
I'll close this now. Feel free to add a comment if this is still happening with the latest builds.
