### ISSUE TITLE
Treeview-main synchronisation not working for network drives

### ISSUE THREAD

**Issue by stephanosio** [derceg/explorerplusplus#191]
The treeview-to-main pane synchronisation feature does not work for mapped network drives (not direct UNC path), even when the "Automatically synchronize treeview with main pane" option is selected.

This feature works for non-network drives and the problem is specific to mapped network drives only.

**Comment by zissakos** [comment]
same here.

**Comment by davidequinel** [comment]
Same here. I have 2 network drives and I can't see them. Version 64 1.3.5.531

**Comment by zissakos** [comment]
any news on this? could this be reproduced? Should I provide more information?
Still doesn't work in 1.4.0.1616

**Comment by NeilSut** [comment]
This still seems to be a problem in the 1.4 beta.

**Comment by InkleDot** [comment]
Still a problem in build 1.4.0.1656, 32 and 64bit.
