### ISSUE TITLE
"Lock Tab" and "Lock Tab and Address" makes program to crash on next run

### ISSUE THREAD

**Issue by irapths** [derceg/explorerplusplus#193]
#### Issue:
If for a tab "Lock Tab" or "Lock Tab and Address" is selected the program will not start the next time.

#### Reproduction:
1. Extract files explorer++_x64.zip and explorer++_x64_symbols.zip in a folder
2. Run Explorer++.exe
3. Select Tools -> Options -> [Tab] General -> Run in portable mode -> OK
4. Navigate inside a folder
5. On tab RClick -> Lock Tab -> Result: Tab icon changes to padlock
6. Close the program
7. Run Explorer++.exe -> Result: APPCRASH

#### Issue found on build:
Explorer++ build is 1.4.0.1324 x64

#### This functionality used to work on:
Explorer++ build is 1.4.0.1176 x64

#### Workaround:
In Config.xml change `Locked` and `AddressLocked` properties to `no` for all tabs.
```<Tab name="0" ... Locked="no" AddressLocked="no" ... CustomName="">```

#### Additional info:
I use application in portable mode with files explorer++_x64.zip and explorer++_x64_symbols.zip extracted in a folder.
The issue is valid also on manual update of the program (replace old build files with new ones) without change the old Config.xml.
I perform the manual update from build 1176 directly to 1324, so I don't know when the problem starts. The only visible difference (I'm sure it is irrelevant) is that the xml file used to be UTF-8 but now is ANSI.

**Comment by lilixiong2018** [comment]
I make a bit change, that seem to work:
```
--- a/Explorer++/Explorer++/ShellBrowser/NavigationController.cpp
+++ b/Explorer++/Explorer++/ShellBrowser/NavigationController.cpp
@@ -272,10 +272,13 @@ HRESULT NavigationController::BrowseFolder(const std::wstring &path, bool addHis

 HRESULT NavigationController::BrowseFolder(PCIDLIST_ABSOLUTE pidl, bool addHistoryEntry)
 {
+// Lilx
+#if 0
        if (m_navigationMode == NavigationMode::ForceNewTab)
        {
                return m_tabNavigation->CreateNewTab(pidl, true);
        }
+#endif

        return m_navigator->BrowseFolder(pidl, addHistoryEntry);
 }
diff --git a/Explorer++/Helper/ContextMenuManager.cpp b/Explorer++/Helper/ContextMenuManager.cpp
index a541fa44..52fdf11f 100644
--- a/Explorer++/Helper/ContextMenuManager.cpp
+++ b/Explorer++/Helper/ContextMenuManager.cpp
@@ -85,8 +85,8 @@ ContextMenuManager::ContextMenuManager(ContextMenuType_t ContextMenuType,
                        IContextMenu2 *pContextMenu2 = NULL;
                        IContextMenu3 *pContextMenu3 = NULL;

-                       pShellExtInit->Initialize(pidlDirectory,pDataObject,NULL);
-                       pShellExtInit->Release();
+                       //pShellExtInit->Initialize(pidlDirectory,pDataObject,NULL);
+                       //pShellExtInit->Release();
```

**Comment by lilixiong2018** [comment]
I create a PR #195, @derceg, please check.
Thank you.

**Comment by derceg** [comment]
Fixed in the commit referenced above.
