### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by alabotski** [derceg/explorerplusplus#196]
Seems program don't work with languages

Download
Explorer++ - 64
Explorer++RU

Run and try open menu
And the program close

**Comment by Twilightssuperb** [comment]
Confirm issue. Same crash. ☹️ Forced to use default language (English).

**Comment by derceg** [comment]
Which version of Explorer++ are you using? If the development version, it's important to only use the DLLs built for that specific version. There's also the possibility that the translation DLLs might be temporarily out of date when using a development build, which could cause crashes like this.
