### ISSUE TITLE
Sort by type in Details does not work

### ISSUE THREAD

**Issue by ericalbers** [derceg/explorerplusplus#197]
When viewing by details, 'File folder' type is always shown first, before 'MP3 Audio File', even when the column Type sort header is clilcked, the Type sort remains the same, where it should put 'File folder' types at the bottom instead of being listed first.

**Comment by derceg** [comment]
This was the case in version 1.3.5, but in 1.4 beta, folders are placed at the bottom when the sort direction changes.
