### ISSUE TITLE
Update homepage to contain a release that is less than 7 years out of date?

### ISSUE THREAD

**Issue by adamgit** [derceg/explorerplusplus#198]
I was recommended to try Explorer++, but the official website is very out of date (and this is supported by e.g. Wikipedia, that states there's been no release since 2013 - making the project appear to be dead).

Could you update the webpage to e.g. point to the unofficial release here: https://explorerplusplus.com/forum/viewtopic.php?f=4&p=5922#p5922 - or even better, ship a release (even if it's alpha)?

Having tried the unofficial package above, the Installer provided is badly broken, but the Explorer++ binary embedded inside it works great, and fixes some obvious bugs in the 2013 release (e.g. it finally works correctly on Retina / HiDPI monitors, which makes a huge difference to new users). It would be great to see this linked from the website (and to update e.g. the Wikipedia page, which probably drives people away before they've even tried it :( )

**Comment by jczanfona** [comment]
https://github.com/derceg/explorerplusplus/releases

**Comment by adamgit** [comment]
That was last updated 7 years ago, and the releases there simply didn't 
work when I tried them on current windows10.

By comparison, the actual versions people are using today DO work on 
Windows 10.

What's the point in listing broken releases, making the project appear 
useless, when in reality it is great and works well?

**Comment by urfausto** [comment]
hi, i also would like to see the website updated, and by the way when is the new version coming out more or less?

**Comment by FolkSong** [comment]
I'm a new user and very confused to see no releases since 2013. Is there a stable build? Is it recommended for everyone to just use the most recent?

**Comment by jczanfona** [comment]
For now you can see the latest version here:
https://github.com/derceg/explorerplusplus#latest-builds

**Comment by jczanfona** [comment]
Also update here is needed:

![image](https://user-images.githubusercontent.com/46503049/77834252-b3b5b900-7143-11ea-9033-82d8dec48826.png)
![image](https://user-images.githubusercontent.com/46503049/77834265-c0d2a800-7143-11ea-817f-429e87a49fe8.png)

**Comment by xnoreq** [comment]
@derceg Even if you don't think 1.4 is "finished" I would suggest uploading at least a 1.4 beta release to github releases and updated the website.

**Comment by derceg** [comment]
I think the development is probably at a point now where a beta release could be made. I've held off on making a release so far, as chunks of the bookmarks functionality haven't worked and so any release would likely have to be marked as alpha.

However, I think the planned bookmarks functionality is all there now, which would pave the way for the next release.

To provide some feedback to the other points raised here:

- The homepage does link to a pretty out of date release, but the development builds are linked to from the [download](https://explorerplusplus.com/download) page. Once there's a beta release, I'll add links to the homepage as well as the GitHub releases section.

- The last release (1.3.5) is what's considered stable. The development version had quite a few bug fixes and improvements, but the bookmarks functionality didn't really work until very recently. My personal view is that the development version has been the better choice for at least several years now, provided you don't need the bookmarks functionality.
However, there have been some significant internal changes made. That's meant that the development version has sometimes had bugs in more basic functionality, though I've tried to fix those once I know about them.
So using the development build might also mean tolerating some new bugs along the way. One thing that helps here is that there are past development builds available, which makes it easy to go back to a previous build if a new one breaks something.

- The update check functionality is very simple at the moment and will hopefully be extended in the future. Currently, it just retrieves the current version number using a text file fetched from the website. I probably won't update that until there's a stable release. Although it would be nice to be able to notify of other releases as well.

**Comment by jczanfona** [comment]
The home page is up to date, with information about the beta version.
I think this issue could be closed if it's okay with you.

**Comment by adamgit** [comment]
Agreed. Although I wish someone would remove the "(beta)" label - as noted at start of this year: the 1.3 release *just does not work* for me on fresh install of Windows10, it's so buggy. Whereas the 1.4 release *actually works*. Pointing people to a so-called 'stable' release which doesn't work isn't great.

But the most important thing is that people can at least now get the working release (if they ignore the misleading 'beta' label), so that's definitely an improvement.
