### ISSUE TITLE
Complete bookmarks

### ISSUE THREAD

**Issue by derceg** [derceg/explorerplusplus#2]
The bookmark system has been partially rewritten and needs to be completed. This is a blocking issue for the next release.

**Comment by zissakos** [comment]
I just wanted to ask what the status of this issue is as this feature is the only one preventing me from using it. Also, there has been a Pull Reuqest fixing bookmarks, any chance it could be pulled in?

**Comment by zissakos** [comment]
any news about this? how about a new release with just the stable stuff that is working (the last one is from 2013)? That would be great!!!!

**Comment by derceg** [comment]
This should now be complete and a beta of the next release should be released soon.
