### ISSUE TITLE
Open each folder in its own tab dose NOT work?

### ISSUE THREAD

**Issue by silaoA** [derceg/explorerplusplus#206]
explorer++ version : 1.3.5_x64 portable。
Windows : Windows 10 1903 Enterprise build 18362.657 64 bit。

I'm new user of explorer++ and have read documentation. I navigate to “Tools > Options" dialog, switch to "tabs" and check the box ”Open each folder in its own tab“, then click Apply and OK.
When I restart explorer++  and  even Windows 10， it seems dose NOT work,  explorer++ still creates a new tab when I double click a folder, and soon many many tabs confuse me.

I'm eagerly expecting an solution. many thanks.

**Comment by sean-e** [comment]
The behavior seems to be correct now, so far as I understand the problem.  Try the latest daily build, on the homepage of the Github repo.

**Comment by derceg** [comment]
This is the intended behavior. The option makes it so that when you double click on a folder, that folder is opened within a new tab.
