### ISSUE TITLE
Application toolbar cannot start powershell

### ISSUE THREAD

**Issue by xnoreq** [derceg/explorerplusplus#209]
Using Explorer++ version 1.4.0.1588 (64-bit build)

Adding "C:\Program Files\PowerShell\7\pwsh.exe" as application to the application toolbar results in a placeholder file icon and nothing happening when clicking the button.

Also, are there any placeholders that can be provided as arguments for the current directory and currently selected files/folders?

**Comment by Zer0XoL** [comment]
I also can not seem to get an application to launch in the current working directory, sad about this lacking feature.

**Comment by derceg** [comment]
Paths with spaces need to be quoted. There are a few changes that have been made in the application that should hopefully make that clearer.

Regarding placeholder arguments, there are none at the moment. I'll use issue #295 to track that.
