### ISSUE TITLE
Which GUI library is used for this project?

### ISSUE THREAD

**Issue by lyldev** [derceg/explorerplusplus#214]
My programming experience is not enough, so I can't find the answer directly from the source code. Can anyone tell me which GUI library is used for this project?

**Comment by linquize** [comment]
Pure Win32 API?

**Comment by lyldev** [comment]
I'm also not sure, I didn't find any signs of using MFC or QT (two GUI libs that I know)

**Comment by sean-e** [comment]
Looks to be entirely hand-rolled Win32 API.

**Comment by sean-e** [comment]
Also wil: https://github.com/microsoft/wil

**Comment by lyldev** [comment]
Thanks a lot to your comments. @sean-e @linquize
