### ISSUE TITLE
When "Show gridlines in details view" is unchecked, vertical column lines remain

### ISSUE THREAD

**Issue by sean-e** [derceg/explorerplusplus#238]
**Describe the bug**
In details view, vertical gridlines remain even though "show gridlines in details view" is unchecked.

**To Reproduce**
1. Go to Tools | Options | Window | Listview
2. Uncheck "Show gridlines in details view", press ok
3. Change view to Details
4. See vertical gridlines separating columns

**Expected behavior**
No vertical gridlines.

**Version (please complete the following information):**
 - Explorer++ version: June 22, 2020 dev 64-bit-build commit 35c3a2bb50c0e0faec42637679c686b989af4403
 - OS: Win 10 1903

**Additional context**
In default light theme, in `ShellBrowser::SetupListView`, the call to `SetWindowTheme(hListView, L"Explorer", nullptr);` causes the vertical lines.  Commenting out that call fixes the issue, but has the side-effect of causing item selection to be colored blue.

In the new dark theme, in `DarkModeHelper::SetListViewDarkModeColors`, the call to `SetWindowTheme(listView, L"ItemsView", nullptr);` causes the vertical lines.  Commenting out that call fixes the issue, but has the side-effect of causing item selection to be colored blue (colored white when inactive), and scrollbar not colored correctly (though it is incorrect with ItemsView window theme as well; Explorer theme does color scrollbars correctly).

**Comment by derceg** [comment]
I'm not sure there's any way of disabling the column lines. It's also something separate from the gridlines. When you toggle the gridlines, that simply adds/removes the LVS_EX_GRIDLINES style.

Without having some supported way of changing what the listview is drawing, I don't think there's much that can be done here.
