### ISSUE TITLE
Toggle menu on/off

### ISSUE THREAD

**Issue by emueyes** [derceg/explorerplusplus#242]
I'm trying to make a minimalist top-level kind of interface, with large shortcut items and as little UI as possible. That's looking really nice, but try as I am going through the source, I can't see how to toggle the main menu on/off. Ideally I'd like it to be like some other programs, not displayed until ALT is pressed,

**Comment by emueyes** [comment]
I've noticed that the Windows Display option doesn't seem to have any effect, is it meant to change the background color of the window? I see in the source it has gradient fill code, so I'm missing something, somewhere.

**Comment by sean-e** [comment]
Explorerplusplus::InitializeMainMenu creates the menu.
When ALT is pressed, Explorerplusplus::WindowProcedure handles the WM_INITMENU.
You might be able to handle display in response to WM_INITMENU.

**Comment by emueyes** [comment]
There so seem to be multiple places where the main menu is added to. I'm be happy to lose bookmarks, or even lose the entire menu system, the inly functions needed could be put onto buttons, or just put onto a context menu, removing the standard Windows context menu, and at the necessary and sufficient would be just 'back', with the entries being references to links in folders where the icons are set etc.

**Comment by i2** [comment]
Sorry to comment on a closed issue, but I didn't want to create clutter.

Is it possible to add this as a feature in E++? (instead of tweaking source code and compiling it)
