### ISSUE TITLE
Window background color

### ISSUE THREAD

**Issue by emueyes** [derceg/explorerplusplus#243]
I've noticed that the Windows Display option doesn't seem to have any effect, is it meant to change the background color of the window? I see in the source it has gradient fill code, so I'm missing something, somewhere.  

I'm on the quest for a simple interface with large icons looking somewhat like a metro app but without the garish colors.

**Comment by sean-e** [comment]
Do you have "View | Display Window" turned on?  That window is rendered with a background gradient.

**Comment by emueyes** [comment]
Yes I just discovered that, it was off before and I just made an assumption. It would still be nice though to fill the listbox/icons panel with some sort of background or backdrop color.  Thanks sean-e

**Comment by emueyes** [comment]
I see this is part of the theme-colors plugin now, very nice. Using 1.4.0.1657 64bit. Now there's another slight issue. The icons render too close to the top of the panel
![exppp](https://user-images.githubusercontent.com/4696327/86200673-b095f300-bba0-11ea-8bac-70214cb96fa3.JPG)

(the dark blue color is my desktop)

I'm really trying to change what perhaps is not what Explorer++ is, in making it shortcut and icon oriented,  but the icon rendering position will affect anyone who changes their theme color so must be found by a few other people at least.
