### ISSUE TITLE
Suggestion : Date format add  yyyy/mm/dd

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#247]
v1.4.0.1637

Date format add  yyyy/mm/dd

Now: Date : 2020/1/1
change to
Date : 2020/01/01

![123](https://user-images.githubusercontent.com/29886853/86936021-0bff4c80-c170-11ea-9fef-fa2b884ec60f.png)

**Comment by kettenfett** [comment]
I wholeheartedly agree. Every Software should implement a date format, that complies with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
| "Date and time values are ordered from the largest to smallest unit of time"

so e.g. 2020-10-13

**Comment by mathieugouin** [comment]
Agree!  And please follow the ISO norm using dahses (-)

**Comment by peter8777555** [comment]
Fixed
