### ISSUE TITLE
About "Detail View" not saving bug

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#248]
I know the bug.

Can i modify the config.xml for "Detail View" ?

**Comment by sean-e** [comment]
the bug is #215?

**Comment by peter8777555** [comment]
I have fixed the problem.

Explorer++ forget to do
From
		<Setting name="ViewModeGlobal">1</Setting>
To
		<Setting name="ViewModeGlobal">4/Setting>

Please fix the REG and config.xml

**Comment by derceg** [comment]
I can't reproduce this in the latest version. Feel free to add a comment here if you're still encountering this.
