### ISSUE TITLE
It is weird TreeView

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#253]
TreeView shows compress files ?

This problem ONLY for 
1. I use TrueCyrpt.
2. I compress whole disk K: (i do not sure,this is problem)

Other disk is OK. (C: D: E: .......)

See picture.

![1](https://user-images.githubusercontent.com/29886853/86546420-6d080400-bf67-11ea-8f00-33803be0e911.png)

**Comment by pseudo555** [comment]
For whatever reason, this is expected behavior.
I remember seing proposed patch to remove them (zip files) from tree view, but i don't think this was merge or option was added to hide zip.

**Comment by derceg** [comment]
As described by pseudo555, this is expected behavior.
