### ISSUE TITLE
Bug : The icon OVERWRITE label text

### ISSUE THREAD

**Issue by peter8777555** [derceg/explorerplusplus#255]
See picture.

Please try Ctrl+T or Ctrl+E for new Tabs.
It always happen at END tab.

![123](https://user-images.githubusercontent.com/29886853/86814318-ced58480-c0b3-11ea-8ccf-f4a154667c53.jpg)

**Comment by derceg** [comment]
I can't reproduce this on Windows 7 or 10. Does it happen on a particular version of Windows? Also is the behavior the same with previous versions of Explorer++?

**Comment by derceg** [comment]
I don't think I've ever encountered this issue, so without further feedback, I don't think there's much I can do.

**Comment by derceg** [comment]
Actually, it appears this happens when fixed width tabs are enabled.
