### ISSUE TITLE
Listview window settings are not applied to many lists

### ISSUE THREAD

**Issue by sean-e** [derceg/explorerplusplus#260]
The 3 settings in the Listview group of the Window page of the Options dialog are not applied to many lists.

1. Disable gridlines on Window page of Options dialog
2. Do a file search
3. The results list uses gridlines

Expected behavior
The results list should not display gridlines

Version (please complete the following information):
 - Explorer++ version: dev build 2020-08-03
 - OS: Windows 10

Additional context
Many places in the code use LVS_EX_GRIDLINES without checking the config.

**Comment by derceg** [comment]
The listview options are specific to the main listview window and aren't really meant to apply anywhere else. The dialogs all use fixed styles.

Making some of the dialogs configurable might be useful. Aside from that, I think the terminology used should be updated (in the options dialog, but also more generally). The treeview is likely better referred to as the navigation pane and the main listview as perhaps the main pane.
