### ISSUE TITLE
The width of the display window cannot be restored

### ISSUE THREAD

**Issue by teuder** [derceg/explorerplusplus#264]
Hi. Thank you for developing a wonderful application.
 
I made the mistake of changing the display window width to the maximum size. I can't get it back to the original width. Can anyone give me any advice on this?

![screen shot 2020-08-06 16495700](https://user-images.githubusercontent.com/2009885/89506626-5e329c80-d806-11ea-95f0-1b150ed8c0d9.png)

**Comment by sean-e** [comment]
Are you able to resize the window by using the mouse to grab the dots in the lower-right corner of the window?

**Comment by teuder** [comment]
Yes. But, even if I resize the window, the display window still fill the entire window.

**Comment by sean-e** [comment]
Try deleting the 3 DisplayWindow* registry values at HKEY_CURRENT_USER\Software\Explorer++\Settings (after exiting the program)

**Comment by teuder** [comment]
Thank you @sean-e! Sorry for my late response.
The problem solved by your advice.
