### ISSUE TITLE
Explorer++ currsor should remember last folder when backing up

### ISSUE THREAD

**Issue by burakyuksek** [derceg/explorerplusplus#267]
Let's say I'm in a folder with 3 other folders.
I click on the second folder.
I press backspace. File explorer returns the currsor to the second folder but explorer++ doesn't. It would be nice if it would.

**Comment by sean-e** [comment]
looks like possible dupe of #212 addressed in PR #223

**Comment by derceg** [comment]
Duplicate of #212
