### ISSUE TITLE
program closes when a FTP folder not available

### ISSUE THREAD

**Issue by owaimori** [derceg/explorerplusplus#269]
when i tried open a FTP folder (which on my phone) if phone not connect to wi-fi at the moment or i dont run a ftp server on it program just closes. 

some error instead would be nice

**Comment by derceg** [comment]
If the application is crashing, please provide a crash dump. Or other information (e.g. which version of Explorer++ you're using).

**Comment by owaimori** [comment]
looks like it was single crash and i dont have that log anymore, but since then it didnt crashes a single time
