### ISSUE TITLE
"open in explorer" buttons dont select a specified file

### ISSUE THREAD

**Issue by owaimori** [derceg/explorerplusplus#270]
i set up explorer++ instead fo windows explorer in the settings and all works fine, but 

(tested with chrome downloads and firefox downloads)
when i select a file iin chrome or firefox download history and click "show in explorer" it just open a folder containing that file in explorer++, but not highlight a file i need. when that folder contain thousand files its very annoying

windows explorer highlight file inside a folder when i do same

**Comment by FuPeiJiang** [comment]
see here https://stackoverflow.com/questions/22118653/shopenfolderandselectitems-for-explorer-replacement-program
I think it is the same for vscode command File: Reveal in File Explorer
they all use SHOpenFolderAndSelectItems

**Comment by sean-e** [comment]
Interesting link there -- it appears that IShellWindows::RegisterPending was key to making it work ( https://docs.microsoft.com/en-us/windows/win32/api/exdisp/nf-exdisp-ishellwindows-registerpending ).  It doesn't look like Exp++ uses IShellWindows at all.
