### ISSUE TITLE
Hotkeys for switching view type not available.

### ISSUE THREAD

**Issue by cdeguise** [derceg/explorerplusplus#278]
In Windows Explorer selecting Shift+Ctrl+N where N is 1-8 will select the various view types (list, small icons, details, etc.).

**Comment by cdeguise** [comment]
So I implemented the "text" for the hotkeys, but didn't commit in PR #279. It wasn't clear if the size was going to be an issue (resolutions, translations, etc.). Thoughts?

![explorer++hotkeys](https://user-images.githubusercontent.com/11948930/97357364-09844800-1870-11eb-8953-577d8fb26629.png)

**Comment by derceg** [comment]
Thanks for the PR, I'll merge it in. Since Explorer doesn't show the accelerators in the menu, I think it's best to do the same and leave them out.
