### ISSUE TITLE
Create a new folder, then type name Enter E++ reports error for path is unavailable

### ISSUE THREAD

**Issue by qwfpbj** [derceg/explorerplusplus#281]
**Describe the bug**
Use F2 to create a new folder, then type Enter E++ reports error for the "new folder" does not exists

**To Reproduce**
1. Go to any folder
2. Use right click to create a new folder, type the folder name to finish
3. Type Enter to go into the newly created folder
4. See error "path is unavailable. If the location is on this PC, make sure the device or drive is connected or the disc is inserted, and then try again. "

**Expected behavior**
Goes into the folder without error occuring. 

**Screenshots**

**Version (please complete the following information):**
 - Explorer++ version: [e.g. 1.4.0.1616 dev (64-bit build)]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by sean-e** [comment]
The steps to repro do not work for me on a dev build.  

Also, the steps do not mention using F2, which is mentioned in the "Describe the bug" section -- so something seems off.

**Comment by qwfpbj** [comment]
I am sorry for the wrong description. It occurs when creating a folder with a folder name typed in very fast, then type enter to go into it with the newly created folder but E++ did not comprehend that the folder name has changed and tries to go to the folder with the original name. The issue also occurs when use F2 to rename a folder, then type Enter to go into that folder, but E++ do not comprehend the folder name change and tries to go to the folder with original folder name, and windows return error "path is unavailable. If the location is on this PC, make sure the device or drive is connected or the disc is inserted, and then try again. "

**Comment by sean-e** [comment]
Ahh, yes, I can repro.  Pressing Enter to open the folder immediately after pressing Enter to commit the name change is key to repro.

**Comment by qwfpbj** [comment]
@sean-e Yes, exactly!

**Comment by sean-e** [comment]
Behavior has changed in Jan 2021.  The rename works properly, but two items are displayed in the items pane, both with the new name.  However, one item is actually an invalid item that still thinks the directory name is New Folder.  That item is the one that remains selected after the Rename operation.  Pressing enter on it causes the error message to appear.  Pressing enter on the other item with the new name works as expected.  I don't recall seeing two items in the items pane after rename before this month.
