### ISSUE TITLE
hey have tested 16+ file apps, this lacks a ton of basic things, here's a google sheet

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [derceg/explorerplusplus#287]
https://docs.google.com/spreadsheets/d/1ngT8No6MBY46QtB9o-45SmqOgH1c3fmzShcVDEt1mvE/edit#gid=0

feel free to add what it does and doesnt do

**Comment by derceg** [comment]
The issues section here isn't really the place for this. Some of the items in the spreadsheet are simple to determine (e.g. whether Ctrl+T opens a new tab), so I think it would be easy enough to figure out the answers on your own.
