### ISSUE TITLE
Does not select corresponding Tab from tasbar...

### ISSUE THREAD

**Issue by mamarilmanson** [derceg/explorerplusplus#288]
**Describe the bug**
When clicking from taskbar the tab I want to go to... I selects the other tab... 

**To Reproduce**
1. Open more than one tab
2. Rearrange the tabs
3. Start choosing a tab from the windows taskbar preview

**Expected behavior**
Select tab that corresponds to the selected tab from the taskbar preview

**Screenshots**

Here, I hovered on the tab C: from the taskbar... but Explorer++ will navigate me to the Downloads Tab
![image](https://user-images.githubusercontent.com/3820189/99869196-0c225500-2c04-11eb-9031-b4c7d8220012.png)

**Version (please complete the following information):**
 - Explorer++ version: 1.3.5.531 (64-bit build)
 - OS: Windows 10
![image](https://user-images.githubusercontent.com/3820189/99869105-6cfd5d80-2c03-11eb-913b-a9285585f4b5.png)

**Comment by sean-e** [comment]
No repro using 1.4.0 dev build.

**Comment by derceg** [comment]
This was fixed for 1.4 beta in b604627471bebc401f4b5ab97e3991394d0ab80b.
