### ISSUE TITLE
[Feature request] option to open different terminal then cmd

### ISSUE THREAD

**Issue by LordMZTE** [derceg/explorerplusplus#296]
I like to use a Terminal emulator different from cmd (alacritty) and it would be nice if the `Open Command Prompt` button could be configured to open it instead.

**Comment by LordMZTE** [comment]
sorry, this shouldn't have the `bug` label

**Comment by derceg** [comment]
I think it would be better to focus on adding parameters to the application toolbar (e.g. as requested in #295). That way, you could add any application you like and have it open the current directory.
