### ISSUE TITLE
Explorer++ doesn't respect the regkey for Disabling NumericalSorting in Explorer

### ISSUE THREAD

**Issue by zissakos** [derceg/explorerplusplus#301]
There is a RegKey with which the NumericalSorting (LogicalSorting) in Windows Explorer can be turned off to have literal/lexicographic sorting.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoStrCmpLogical"=dword:00000001

When set, Windows Explorer does respect it, but Explorer++ does not.
See this example with the same folder open in WinExp and Exp++:

![image](https://user-images.githubusercontent.com/24368712/103366857-eb330680-4ac3-11eb-80ae-96d2dddfb75d.png)

Could this please be made possible?

**Comment by zissakos** [comment]
There is a RegKey with which the NumericalSorting (LogicalSorting) in Windows Explorer can be turned off to have literal/lexicographic sorting.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"NoStrCmpLogical"=dword:00000001

When set, Windows Explorer does respect it, but Explorer++ does not.
See this example with the same folder open in WinExp and Exp++:

![image](https://user-images.githubusercontent.com/24368712/103366857-eb330680-4ac3-11eb-80ae-96d2dddfb75d.png)

Could this please be made possible?

**Comment by derceg** [comment]
There is a related pull request for this sort of functionality in #53 (I know you're already aware of it zissakos, but just in case anyone else looking at this issue doesn't know).

On the subject of whether Explorer++ should attempt to read configuration values set by Explorer, my view is that it's not worthwhile, for a few reasons:

1. Explorer can effectively be considered to be just another independent application. Its configuration values are specific to it.
2. The registry keys used to store the configuration can change at any point in time and might change between different version of Windows.

Having said that, there might be some documented way Windows exposes this configuration value.

**Comment by derceg** [comment]
Closing, since this functionality was effectively implemented through #53.
