### ISSUE TITLE
Crash when copying from Phone

### ISSUE THREAD

**Issue by martinstingl** [derceg/explorerplusplus#306]
When I copy a file from my phone (see screenshot), Explorer++ crashes when I paste the file somewhere.
Pasting the file into a normal Explorer window crashes the Windows process explorer.exe.

[image](https://user-images.githubusercontent.com/1312947/104899255-e8b52580-597a-11eb-92aa-de5cb03f56fc.png)

**Crashes**
No Explorer*.dmp file was created in %temp%

**Version (please complete the following information):**
Explorer++ version 1.4.0.1759 dev (64-bit build)
Build date: Dec 14 2020 20:34:45
 - Windows 10 64Bit

**Comment by derceg** [comment]
I can't reproduce this. Does the issue still occur when using the latest build?

**Comment by martinstingl** [comment]
No, it does not occur anymore with the current version:
Explorer++ version 1.4.0.1874 dev (64-bit build)
Build date: Oct 30 2021 15:38:46

Thank you
