### ISSUE TITLE
Dark Color Scheme

### ISSUE THREAD

**Issue by dougransom** [derceg/explorerplusplus#308]
I suggest adding a dark color scheme to use at night, that once can easily switch too, with readable default colors.

**Comment by dougransom** [comment]
i can't figure out how to change the label, it should be ehancment, not bug.

**Comment by i2** [comment]
If you mean dark theme, check this out: https://github.com/derceg/explorerplusplus/issues/115

**Comment by derceg** [comment]
Duplicate of #115
