### ISSUE TITLE
[regression] Rename of item leaves invalid item entry in the item view

### ISSUE THREAD

**Issue by sean-e** [derceg/explorerplusplus#309]
**Describe the bug**
Renaming a directory or file causes an extra item to appear in the items pane.

**To Reproduce**
1. Enable details view
2. select a directory in the items pane
3. press F2 and rename the directory, then press enter to commit the change
4. two entries with the new name are now listed in the pane

**Expected behavior**
Only one entry should be listed for the directory

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0 dev (64-bit build) as of 2021-01-20
 - OS: Windows 10 20H2

**Additional context**
Related to #281 
Potentially related to commit 09c0281 or commit 0427a39
Pressing F5 clears the extra item

**Comment by sean-e** [comment]
While working on PR #311 I noticed that this bug does not occur when drive monitoring is disabled for a drive.

**Comment by cheeseandjamsandwich** [comment]
This behavior is the same when renaming files too.  Not just folders.
Rename a file, and a duplicate item appears above it, moving the current item down (sorted by name, ascending).  F5-refresh removes it.

Using the new build today:   Explorer++ version 1.4.0.1805 dev (64-bit build) 
And the builds going back 10-15 days too.  I haven't determined which build it started in yet... Will try to.

**Comment by cheeseandjamsandwich** [comment]
The bug looks to have been introduced in 1.4.0.1800, and present up to the current 1.4.0.1805
If i uninstall E++ and reinstall 'Explorer++ version 1.4.0.1798 dev (64-bit build)', it's working normally.

Before, i was just letting E++ 'Remove' the installation when trying to install an older build, but then installing that build meant that the behavior was still present.  This confused me lots.  A standard uninstall allows successful 'rolling back'.
