### ISSUE TITLE
When right click in the directory under Windows 7 64bit, "The explorer ++ is stopping work" window appears

### ISSUE THREAD

**Issue by yosaku01** [derceg/explorerplusplus#310]

**Comment by jczanfona** [comment]
I suppose this issue can be closed. Isn't it?

**Comment by derceg** [comment]
This is likely a different issue (probably one to do with an interaction with an individual shell extension).

The reason for the crash in #316 is that the way in which the context menu is built on Windows 8+ has completely changed. On Windows 7, however, the menu is still built in the same way as before. Which means that the background context menus are now completely different and are built in different ways.

**Comment by derceg** [comment]
It's hard to say what's causing this without a crash dump or more information, so I don't think there's much I can do here.
