### ISSUE TITLE
Right-clicking before completing a left-click doesn't show the context menu

### ISSUE THREAD

**Issue by tbttfox** [derceg/explorerplusplus#312]
On any file or folder in either the tree view or folder view
Left click down
Right click down
Left click up
Right click up

Notice no context menu shows up. It should. I'm using the latest 1.4.0 beta

This is one of those minor polish things that doesn't seem like it would matter, but I really think it does, especially when the built in explorer allows it. And it matters more in the tree view when you would want to both go to a folder, and right-click on it.

**Comment by jczanfona** [comment]
To me is causing a crash
Ussing v1.4.0.1806

**Comment by derceg** [comment]
@jczanfona Please file a new issue with more information.

**Comment by jczanfona** [comment]
Done in https://github.com/derceg/explorerplusplus/issues/316
