### ISSUE TITLE
Tab Bar Always Visible

### ISSUE THREAD

**Issue by WildByDesign** [derceg/explorerplusplus#314]
**Describe the bug**
The **Always show the tab bar** setting has not been functioning correctly in recent builds. Particularly, it has not been working correctly since the commits (https://github.com/derceg/explorerplusplus/issues/303) related to background/foreground tabs.

**To Reproduce**
1. Uncheck the **Always show the tab bar** setting and the tab bar hides correctly.
2. Close Explorer++ and reopen Explorer++.
3. The tab bar is visible again.

**Expected behavior**
Tab bar should remain hidden when the **Always show the tab bar** setting is unchecked.

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1800 dev (64-bit build) recent AppVeyor build
 - OS: Windows 10 Version 20H2 64-bit

**Additional context**
I use Explorer++ as portable using the **config.xml** file. The relevant line:
`<Setting name="AlwaysShowTabBar">no</Setting>`
shows correctly but still tab bar reappears at every launch.

**Comment by derceg** [comment]
I can't reproduce this, either in the version given above, or in the latest build. Are you able to provide a simple config.xml file that demonstrates the issue? (Since it might rely on a particular combination of options being set).

**Comment by WildByDesign** [comment]
Thank you for your response, @derceg I appreciate it.

I have figured out how to reproduce this issue consistently and also figured out a temporary workaround. I only use Explorer++ in portable mode (config.xml), so I cannot confirm if it also affects the standard registry settings or not. So please use portable mode to reproduce first.

It seems to be related to: Options - General - On Startup - **Load default folder**

If I use **Load default folder**, the issue reproduces everytime. The **Always show the tab bar** setting makes the change in the config.xml file, but once you restart Explorer++, it literally removed that setting directly from the config.xml file and the tab bar returns everytime.

**Workaround:** Options - General - On Startup - **Load previous tabs**

The **Load previous tabs** startup option fixes (workaround) the issue. It also allows the **Always show the tab bar** option to stay within the config.xml file without the setting getting deleted upon next execution of Explorer++.
