### ISSUE TITLE
Crash on Right click

### ISSUE THREAD

**Issue by jczanfona** [derceg/explorerplusplus#316]
**Describe the bug**
Explorer ++ crashes when right click and then dump file is created

**To Reproduce**
In the right pane, pressing the right mouse button on a free space (not on any file)

**Expected behavior**
Show the context menu

**Crashes**
Explorer++1.4.0.1806-30012021-201121.dmp
<details>
<summary>Details</summary>

[Explorer++1.4.0.1806-30012021-201121.dmp.zip](https://github.com/derceg/explorerplusplus/files/5898567/Explorer%2B%2B1.4.0.1806-30012021-201121.dmp.zip)

</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/46503049/106365464-1b293000-6336-11eb-8534-1d09929c57a0.png)

**Version (please complete the following information):**
 - Explorer++ version: v1.4.0.1806 dev (64-bit build)]
 - OS: Windows 10

**Additional context**
None

**Comment by jczanfona** [comment]
Same in https://github.com/derceg/explorerplusplus/issues/310

**Comment by jczanfona** [comment]
The problem continues in v1.4.0.1817 x64

**Comment by derceg** [comment]
Can you attach the crash dump?

**Comment by jczanfona** [comment]
[Explorer++1.4.0.1817-03022021-210732.dmp.zip](https://github.com/derceg/explorerplusplus/files/5921189/Explorer%2B%2B1.4.0.1817-03022021-210732.dmp.zip)

**Comment by jczanfona** [comment]
Right, well done (1818)
Tx a lot !!

**Comment by derceg** [comment]
Great, glad it now works.
