### ISSUE TITLE
[Feature Request] Ability to scroll tab list with mouse

### ISSUE THREAD

**Issue by EliEron** [derceg/explorerplusplus#321]
When the tab list overflows you currently have to scroll the list using buttons on the right of the list, it would be quite useful if scrolling the mouse wheel while hovering over the tab bar would scroll it back and forth.

This is how the tab list in Firefox and a number of Linux file managers work. As a I frequently have a lot of tabs open at once that I switch between this would help me out massively. In fact it's pretty much the only lacking feature I have found in Explorer++, as I have found it to function exactly as I would like it to otherwise. 

Thank you so much for all the work you are putting into this project.

**Comment by derceg** [comment]
This was implemented in 4d2d1808d5cea4cbec9c2b794160bb5302f4158e.
