### ISSUE TITLE
Is Explorer++ dead?

### ISSUE THREAD

**Issue by kettenfett** [derceg/explorerplusplus#343]
What has happened to the developers? Last update is from march '21.
Is development halted, did they create a new repository or is this software dead?

**Comment by derceg** [comment]
No, it's not dead. I'm often busy with work throughout the year, so it's not unusual for me to take a break for several months. It's also generally how I prefer to work on the project - a few months on, followed by a few months off.

**Comment by kettenfett** [comment]
Can't even tell you how happy I am to hear this! 
Explorer++ has been my favourite explorer the past 2 years, and by now, it would be a pain for me to replace it - and I tried many before and after I found Explorer++.
