### ISSUE TITLE
Feature request: Hightlight/Select previous folder after navigating upward.

### ISSUE THREAD

**Issue by kettenfett** [derceg/explorerplusplus#345]
Have an option to highlight the folder I navigated up from, whenever Up is used.

This has become sort of essential in my mind, especially when working with folders which have many subfolders.

**Comment by Pysis868** [comment]
Was feeling this and realized because Windows Explorer has this feature.

**Comment by kettenfett** [comment]
Hurrey, it's working in the latest AppVeyor Snapshot. (version 1.4.0.1879)
Link to AppVeyor Snapshot: https://ci.appveyor.com/project/derceg/explorerplusplus/builds/41424895
