### ISSUE TITLE
Issue at setting Explorer++ v1.4.1 as default File Manager (all folders)

### ISSUE THREAD

**Issue by J-Porras** [derceg/explorerplusplus#346]
Description
Instead of opening Explorer++ after replacing the default File Manager it shows an error message saying "Explorer++ has encountered an error", 

**To Reproduce**

1. Go to 'Tools'
2. Click on 'Options'
3. Click 'Replace Explorer for all folders'
4.Accept the warning message
5.Try to open any Windows folder on Desktop (it crashes), Win + E stills works 

**Version (please complete the following information):**
 - Explorer++ version: [1.4.1.(64-bit build)]
 - OS: [e.g. Windows 10 v 19042]

Screenshots and dump file 
![errorMessage](https://user-images.githubusercontent.com/70417964/135580834-0ca4ff9b-0fa9-4c3c-b46c-30d1c93856cd.png)
[Explorer++1.4.0.1866-01102021-010712.zip](https://github.com/derceg/explorerplusplus/files/7264963/Explorer%2B%2B1.4.0.1866-01102021-010712.zip)

**Comment by zengqu** [comment]
another bug is when I use explorer++.exe to replace the default file explorer of the system, I open the folder where the cpp file is located in visual studio, and cannot locate the specific cpp file.
and **sometimes it wast a long time to open the folder**.

**Comment by derceg** [comment]
Sorry, AppVeyor only keep builds from the last month and I need the symbols from the build to investigate the crash dump. Are you able to upload a crash dump from the latest build?

**Comment by yashpalgoyal1304** [comment]
hi @derceg it's awesome to see u active on the tracker. i thought that the project was not maintained, but glad to see it is. eagerly waiting for a new release of E++. awesome. keep up.

**Comment by goyalyashpal** [comment]
@J-Porras hi! please "close as not planned" - by reopening & picking this one from drop down on close button.
