### ISSUE TITLE
Additional file instance after update

### ISSUE THREAD

**Issue by irapths** [derceg/explorerplusplus#352]
**Describe the bug**
When the directory of a file is open, new instance of the file is added every time it is updated (edit-save).

**To Reproduce**
1. By using E++ open a directory with file "document.docx"
2. Edit and save file "document.docx"
3. Issue: 2 instances of file "document.docx" are in directory

**Expected behavior**
Single instance of file "documents.docx" is in directory after update.

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1879 dev (64-bit build)
 - OS: Windows 10 21H2

**Additional context**
I use application in portable mode with file explorer++_x64.zip extracted in a directory.
I don't know when this issue first appeared but is there for some builds now.
Happens if the file is updated with application like MSOffice (Word/Excel/... ), LibleOffice (Writer/...), even if is single txt, but not if is txt and edited with Notepad, Wordpad, N++.

**Comment by kettenfett** [comment]
Can confirm. A duplicate is created everytime a file is edited&saved.
With MS Office files, this can get messy real quick:
![grafik](https://user-images.githubusercontent.com/23098362/146154242-d4e22d07-d7f7-489e-920d-b7880179edfa.png)

I also testet with image editing and txt files: No Dupes are created. It seems to be mostly with MS Office files.
