### ISSUE TITLE
Explorer++ does not start in Session 0

### ISSUE THREAD

**Issue by LunarResearch** [derceg/explorerplusplus#353]
Hello!
Since version 1.4.0.1819 Explorer++ does not start in Session 0.
When trying to run from KernelExplorer gives the following error:
Could not convert: --application-crashed = 6716,2176,0x0┬а000┬а00B┬а2A4┬аFBB┬а2A0,C18A8DE2-2573-43EF-9319-61D19D00A871
Run with --help for more information.
Please fix the bug.

**Comment by derceg** [comment]
I can't reproduce in Windows 7 - the application starts correctly in session 0. It's likely this was fixed by 1a823471065599d2c8314ce66573a2b2422919ac.
