### ISSUE TITLE
Win11 only - "folders" in toolbar display issue

### ISSUE THREAD

**Issue by pseudo555** [derceg/explorerplusplus#354]
**Describe the bug**
The folders button in e++ toolbar doesn't look right.
Might be related to dark theme use.

**To Reproduce**
1. Start explorer++
2. Check toolbar

**Expected behavior**
Icon looks like the other one. Or the same as on win10.

**Screenshots**
![epp-displayIssue](https://user-images.githubusercontent.com/18347988/149622881-e69fc748-e444-49cb-967b-47e2ae12904c.png)

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1848 dev (64-bit build)
 - OS: Windows 11

**Comment by pseudo555** [comment]
in fact, hoovered icon and normal one were swap. if you put your mouse cursor over that button, the blue background disapear.
The behavior is simly reversed from what is expected.

**Comment by derceg** [comment]
This looks like it's expected. The button is in the pressed state while the folders view is being shown, so the fact that it has a different background color is normal. The button will also be displayed in a similar sort of way on Windows 10 when the folders view is being shown.

**Comment by derceg** [comment]
The only real difference seems to be the highlight color, which does make the text harder to read. Is it that specifically, or something else?

**Comment by pseudo555** [comment]
Only the  highlight color. The blue in win 11 is really aggressive compared
to the win 10 version.

**Comment by WildByDesign** [comment]
This is an issue that seems to affect programs that use win32-darkmode like Explorer++, Notepad++ and also LibreOffice. It's actually a change that Microsoft made in their aero.msstyles theme file, unfortunately. Those programs all have this issue on Windows 11 in dark mode.

I don't know if there is a way to programmatically use a different button resource within the aero.msstyles file or not.

**Comment by pseudo555** [comment]
w11 bug in fact, see https://github.com/derceg/explorerplusplus/issues/115#issuecomment-1598660527 for details
