### ISSUE TITLE
Feature request: option to show single tab only on taskbar

### ISSUE THREAD

**Issue by dave-ostroske-at-microbac** [derceg/explorerplusplus#356]
Hi, I have been using explorer++ for a while now, and I really like it.

I have one particular issue, though. When I hover over it on the Windows taskbar, I see separate windows for each tab. That's not a problem. But my problem is related: when I focus on explorer++ with a hotkey like Super+1 (i.e. the Windows key and the number 1 at the same time), then explorer++ switches to the very first tab, and not the tab that I was previously working on. I could slide the active tab to the left if I want to go to another app, but I'm prone to forget to do this.

Other Windows applications with multiple tabs will opt to keep the current tab active, then switch back to it when the app is focused again. I would prefer to have this be the default behavior, though an option to display only a single tab at a time would also be welcomed.

Would it be possible to incorporate such a change into how the app works, either by a setting or by default behavior? It would make me much more productive.

Thank you for your time and attention, and I look forward to hearing others' feedback.

**Comment by sean-e** [comment]
You can disable the tab previews: uncheck "Tools | Options | Tabs | Show taskbar thumbnails"
When unchecked, Win+number just brings exp++ to the foreground without changing the active tab.

**Comment by dave-ostroske-at-microbac** [comment]
Perfect, thank you! That's exactly what I needed. Wish you well!
