### ISSUE TITLE
Long path/filenames are not sorted correctly

### ISSUE THREAD

**Issue by GitttyWS** [derceg/explorerplusplus#357]
Win 10
Explorer ++ Version 1.3.5.531 (64-bit Unicode build)

I just tried this tool. The first thing I realized is:

I have very deep folders that endup with about 267 characters. 
e.g. x:\00_xx_xxxxx\xxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxx_!!!xxxxxxxxxxxxxxxxx_!!xxx_xxxxxxxxxxxxxxxxxx_xxx\!!!!!xxxxxxxxxxxxxxxxxxxxxx_xxxxxx_xxx\20210415_!!!!!!!!!xxx xxxxxxxx - xx xxxxxxxxxxx xx xxx xxxxxxxx xxxxxxxxxxx xxxxxxxxx xx xxxxxxxxx xxxx.pdf

If I see the detailed view they those files are not sorted according to their name. All such long filenames also show the date 01.01.1601, 02:00:00

The original file explorer shows them in the correct order.

This might be a bug.

**Comment by derceg** [comment]
Long paths (longer than 259 characters) aren't currently supported. Though, checking in the most recent dev version, dates are shown correctly and items are sorted correctly when in a folder with a long path. So I don't think this is an issue any longer.
