### ISSUE TITLE
What is the background_thread_enumeration branch? Has the main branch added threading?

### ISSUE THREAD

**Issue by Crogarox** [derceg/explorerplusplus#361]
From what it implies, does this program support multiple threads or is it all one thread?

Also, keep up the good work! I still find this program very useful!

**Comment by derceg** [comment]
It was an experiment to perform folder enumeration on a background thread. The changes haven't been made on master so far.

In terms of threading in general, there's always been work that's been done on a background thread (e.g. to retrieve file icons), so the application has never really been single threaded.
