### ISSUE TITLE
Crash when click option.

### ISSUE THREAD

**Issue by Mishasama** [derceg/explorerplusplus#374]
**Describe the bug**
As title.

**To Reproduce**
1. Click on 'Tool'
2. Click on 'Option'
4. See the error

**Expected behavior**
Do what it should be.

**Crashes**
[Explorer++1.4.0.1961-03122022-180422.zip](https://github.com/derceg/explorerplusplus/files/10146068/Explorer%2B%2B1.4.0.1961-03122022-180422.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/54498172/205433679-cdc68f17-ea4c-49e2-acfd-e14864f2902c.png)

**Version (please complete the following information):**
 - Explorer++ version: 1.4.0.1961 dev (64-bit build)
 - OS: Windows 10

**Additional context**
It happens after update from the beta version.

**Comment by derceg** [comment]
Are you using a translation DLL from a previous version? It looks like it's crashing because a resource can't be loaded, which can happen if you use an older translation DLL.

**Comment by Mishasama** [comment]
> 

Then what should I do? I can't go to the option to change back to English.
