### ISSUE TITLE
Lose keyboard focus upon launching Explorer++

### ISSUE THREAD

**Issue by tmthywynn8** [derceg/explorerplusplus#380]
**Describe the bug**

When launching Explorer++ version 1.4.0.1962 dev (64-bit build), the keyboard focus does not land on any controls. As a screen reader user, e.g., Narrator, this makes navigation rather complicated. This is not the case with Explorer++ version 1.4.0.1748 beta (64-bit build).

**To Reproduce**

1. Launch Explorer++. With my configuration, it opens the default folder, This PC.
2. *Tab* around to see if you can get to any of the controls, e.g., the address combo-box, folder tree-view, items list-view, etc.
	* Expected: I should hear controls being announced.
	* Actual: I hear nothing.
3. Press some letters to see if first-letter navigation occurs. 
	* Expected: focus should be moved to a file or folder.
	* Actual: The Default Beep sound plays, as if there is nothing there.
4. Press *Alt+D* to move to the address bar. This actually works.
5. Press *Tab* to move among controls. This also works.
6. Tab to the list-view, press some letters for first-letter navigation, find a folder, and enter it with *Enter*.
	* Expected: the Complete Navigation sound would play.
	* Actual: It just goes into the folder without playing a sound.
7. Exit with *Alt+F4*.
	* Expected: It gracefully exits.
	* Actual: I got it to crash once. I since reverted back to the latest released beta build, so no idea how often that would happen.

**Crashes**

[crashDump.zip](https://github.com/derceg/explorerplusplus/files/10528163/crashDump.zip)

**Version:**

* Explorer++ version: 1.4.0.1962 dev (64-bit build)
* OS: Windows 10: Version 22H2 (OS Build 19045.2486)
* Screen readers used: Narrator (launched with *Control+Windows+Enter*) and [NVDA](https://github.com/nvaccess/nvda)

**Comment by derceg** [comment]
Thanks, I've been able to reproduce the focus issue, so I'm looking at fixing that now. About the crash, unfortunately, AppVeyor only keep build artifacts for a month, so I don't have symbols for version 1.4.0.1962 and can't do much with the crash dump. I'm hoping to figure out somewhere else I can keep dev builds and their symbols long-term, but in the meantime, if you see the crash again in a newer dev version, please file a new issue with the crash dump.
