### ISSUE TITLE
Can you transfer the project to CMake build system?

### ISSUE THREAD

**Issue by Tangwego** [derceg/explorerplusplus#392]
building in other system. vs is not supported

**Comment by derceg** [comment]
Hi Tangwego, which system did you have in mind? You would still need to install the C++ build tools at least, even if you don't install the full IDE.

**Comment by Tangwego** [comment]
I need run it on Iot device like Raspberry Pi, and my host device is using Raspberry Pi too.

**Comment by Tangwego** [comment]
my operating system is a simple linux,  create by myself...
