### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by BlueIncog** [derceg/explorerplusplus#397]
Hi, I am having trouble compiling this program, would anyone be able to build the latest commit and add it to the releases page?

**Comment by derceg** [comment]
Builds are available on [AppVeyor](https://ci.appveyor.com/project/derceg/explorerplusplus/branch/master), so you can download the build for the latest commit from there.

What was the issue you had with compiling? I can update [BUILDING.md](https://github.com/derceg/explorerplusplus/blob/master/BUILDING.md) if there's something that's unclear.

**Comment by BlueIncog** [comment]
I was trying to compile using VS Build tools (cli tools) instead of Visual Studio itself, so I was having some trouble.
Thank you for clearing up where I could find the latest release, I couldn't survive without Explorer++ lol
