### ISSUE TITLE
Treeview does not update when removing a folder selected in treeview

### ISSUE THREAD

**Issue by MIRK0** [derceg/explorerplusplus#399]
**Describe the bug**
Treeview is not updated when a folder is deleted from Treeview

**To Reproduce**

- Select a folder from Treeview
- Press Ctrl+Del and remove it
- Folder will disappear from the main view, but not from treeview. When is selected from treeview it will report an error because missing folder. Also Refresh action does not update treeview.

**Expected behavior**
I'd expect the folder (and subfolders) to disappear from Treeview when deleted.

**Version:**
- Explorer++ version: 1.4.0.1748 beta (64-bit build)
- OS: Windows 11

**Comment by derceg** [comment]
The directory monitoring code for the treeview has been overhauled in more recent dev versions. Does this issue still reproduce if you try it in the current dev version? Note there is a bug in the current dev version that causes an item in the treeview not to be deleted when you press Del, but you can right-click on an item in the treeview and select delete from that menu instead.

**Comment by MIRK0** [comment]
I confirm that with the recent dev version 1.4.0.2210 dev (64-bit build), using right-click - Delete, the folder is indeed removed from Treeview. I also confirm the bug that do not process Ctrl+Del or Del commands (it jumps back to the parent dir, selecting it)

**Comment by MIRK0** [comment]
> I also confirm the bug that do not process Ctrl+Del or Del commands (it jumps back to the parent dir, selecting it)

This bug is still present in 1.4.0.2283 dev (64-bit build), just to le you know.

**Comment by MIRK0** [comment]
Fixed in 1.5.0.2375 dev (64 bit)
