### ISSUE TITLE
During program debugging, It killed the game COD16 in my memory .

### ISSUE THREAD

**Issue by xj123home** [derceg/explorerplusplus#420]
During program debugging, It killed the game COD16 in my memory and kicked it out of the memory.

**Comment by derceg** [comment]
When debugging on my machine, Visual Studio tends to use a lot of memory, but the memory usage of Explorer++ itself is still very low. I'd guess that something similar is happening here. Without further information (e.g. how much memory Explorer++ specifically is using, how much RAM you have), I don't think there's much I can do.
