### ISSUE TITLE
Crash when changing folders

### ISSUE THREAD

**Issue by zeibloup** [derceg/explorerplusplus#429]
explorer++ 1.5.0 2299 crash. It was opened during longtime
[Explorer++1.5.0.2299-08022024-160942.dmp](https://github.com/derceg/explorerplusplus/files/14211243/Explorer%2B%2B1.5.0.2299-08022024-160942.dmp)
### **Describe the bug**
A clear and concise description of what the bug is. Please check whether the bug is still present in the latest dev version before filing.

**To Reproduce**

**Expected behavior**

**Crashes**
Please attach the associated crash dump. This file should be created in %temp% and be named something like Explorer++1.4.0.0-11102020-194414.dmp. Not attaching a crash dump may make it significantly more difficult to diagnose the cause of a crash.

**Screenshots**

**Version (please complete the following information):**
 - Explorer++ version: [e.g. 1.4.0.1616 dev (64-bit build)]
 - OS: [e.g. Windows 10]

**Additional context**
explorer++ 1.5.0 2299 64bit, Windows 11

**Comment by derceg** [comment]
There's only two cases I can think of that would trigger a crash like the one shown in the crash dump:

1. A bug in the listview control.
2. (More likely) A memory corruption bug somewhere else.

Given that, I don't think the crash dump is giving an accurate indication of where the core issue actually occurred and I don't think there's anything I can do.

@zeibloup If you discover any other information about the crash (e.g. a specific way of triggering it), feel free to post here.
