### ISSUE TITLE
Crash on startup after removing USB drive

### ISSUE THREAD

**Issue by abarbieriswlg** [derceg/explorerplusplus#453]
**Describe the bug**
I set up Explorer++ to remember open tabs, so it reopens them at start.
Today I was working with a removable drive, and had one tab open on the drive.
After removing the drive, starting E++ crashes and gives no option to "forget" the bad path and close the corresponding tab

**To Reproduce**
1) Connect a removable drive and see the assigned letter, e.g. F:
2) Open Explorer++
3) select F:
4) Close Explorer++
5) Remove the drive via "Safely remove hardware"
6) Try to start Explorer++: it will crash
7) Add the drive back in: Explorer++ will start and show the drive root

**Expected behavior**
The program should:
1) display a warning about the missing drive (optional)
2) start. 
   If the missing drive was on the only tab, it must automatically switch to a default folder (C:\, or the Desktop)
   If there were multiple open tabs, you can also switch bad tabs to the default folder, or close them

**Version (please complete the following information):**
 - Explorer++ version: 1.5.0.2408
 - OS: Windows 11

**Comment by derceg** [comment]
Hi, thanks for the report. Explorer++ should already mostly handle situations like this. If, for example, a directory is deleted and Explorer++ is re-opened, an error message should be shown and the relevant tab should navigate to the new tab directory. The handling isn't great for things like network drives, where you can have to wait a while for the operation to time out, but it should generally work.

If the application is crashing, it sounds like something else is going wrong. Is a crash dump produced at all?

**Comment by abarbieriswlg** [comment]
Hi,

sorry I forgot to attach the dumps.
On my machine it's very easy to reproduce with the steps above. To obtain the last one, I just used a simple USB stick, closed E++, removed the stick, and started program again.

thank you.
(and, by the way, I totally love it. There are a few improvements I would make, but great work)

[Explorer++1.5.0.2408-23052024-141739.dmp](https://github.com/derceg/explorerplusplus/files/15418838/Explorer%2B%2B1.5.0.2408-23052024-141739.dmp)
[Explorer++1.5.0.2408-23052024-141757.dmp](https://github.com/derceg/explorerplusplus/files/15418839/Explorer%2B%2B1.5.0.2408-23052024-141757.dmp)
[Explorer++1.5.0.2408-23052024-144241.dmp](https://github.com/derceg/explorerplusplus/files/15418840/Explorer%2B%2B1.5.0.2408-23052024-144241.dmp)
[Explorer++1.5.0.2408-23052024-170842.dmp](https://github.com/derceg/explorerplusplus/files/15418842/Explorer%2B%2B1.5.0.2408-23052024-170842.dmp)
