### ISSUE TITLE
Request: option to use non-"logical" sort order

### ISSUE THREAD

**Issue by cxw42** [derceg/explorerplusplus#46]
System: Win8.1 x64
Explorer++ version 1.3.5.531 (32-bit Unicode build) of 03/02/2013 21:13:37

First of all, nice work!  Second, I would like to request an option to use the non-"logical" sort order for sorting by name.  

Conditions: I have a directory with filenames starting with "18," "19," "1A," and "1B."  
Observed behaviour: The "1A" and "1B" sort before the "18" and "19" because the number 1 is smaller than 18 or 19.  This is the behaviour of [StrCmpLogicalW](https://msdn.microsoft.com/en-us/library/bb759947%28VS.85%29.aspx) (see [this answer](http://stackoverflow.com/a/4314191/2877364) by [hmuelner](http://stackoverflow.com/users/324065/hmuelner)).  
Requested behaviour: "1A" should sort after "19".  Specifically, would it be possible to use [StrCmpI](https://msdn.microsoft.com/en-us/library/bb759942%28v=vs.85%29.aspx) instead per an option setting?  It appears to be in [ShellBrowser/SortManager.cpp](https://github.com/derceg/explorerplusplus/blob/43e90624af673254e43c2aaf898f2c81eab5ff9d/Explorer%2B%2B/ShellBrowser/SortManager.cpp) lines 338, 379, and 386 (plus elsewhere, but those don't appear relevant to my specific request).

Thank you for your consideration!

**Comment by derceg** [comment]
I think this could be a worthwhile addition and I'm happy to review a pull request that provides an implementation.

**Comment by zissakos** [comment]
disappointed to see that this activity/pull request was abandoned. I need this ! :-)
Anyone working on it/what must be done now?

**Comment by zissakos** [comment]
Actually, why doesn't explorer++ just inherit the sort order from Windows?
Windows supports both sort orders (alphanum and logical), which can be changed with a registry key.
It is confusing to open a folder in both explorer++ and WindowsExplorer and find that the sort order is different. Even the dir command in the command window follows the registry setting.
