### ISSUE TITLE
Crash when switching to dark mode on ARM64

### ISSUE THREAD

**Issue by Frodojj** [derceg/explorerplusplus#478]
**Describe the crash**
Crash with version 1.5.0 (arm64) downloaded from github and unzipped to downloads/explorerpp_arm64 folder.

**To Reproduce**
Steps to reproduce the crash:
1. Go to Tools -> Options -> Appearance
2. Change Theme to "System Default"
3. Click Apply.

**Version (please complete the following information):**
 - Explorer++ version: 1.5.0.2483 dev (ARM64 build)
 - Build date: Sep 14 2024 00:10:58
 - OS: Windows 11

**Additional context**
 - Crash dump 1 (when noticed): [Explorer++1.5.0.2483-15092024-144440.dmp](https://github.com/user-attachments/files/17007038/Explorer%2B%2B1.5.0.2483-15092024-144440.dmp)
 - Crash dump 2 (when reproduced): [Explorer++1.5.0.2483-15092024-144739.dmp](https://github.com/user-attachments/files/17007034/Explorer%2B%2B1.5.0.2483-15092024-144739.dmp)

**Comment by Frodojj** [comment]
Also occurred when setting theme to dark (I use dark mode on my computer):

[Explorer++1.5.0.2483-15092024-145824.dmp](https://github.com/user-attachments/files/17007055/Explorer%2B%2B1.5.0.2483-15092024-145824.dmp)

**Comment by derceg** [comment]
Hi Frodojj, could you try the build available [here](https://ci.appveyor.com/project/derceg/explorerplusplus/builds/50614101/job/k5qh9u5o8xelc3tw/artifacts) and see if it fixes the crash?

**Comment by Frodojj** [comment]
That fixed it! Thank you.
