### ISSUE TITLE
New folder creation issue in Windows 10

### ISSUE THREAD

**Issue by dutenhnj** [derceg/explorerplusplus#48]
When you right click to create a new folder, normally it would create "new folder", select it and jump directly to editing the name, however in Windows 10 explorer++ misses the renaming step entirely and instead just creates "New Folder" without selecting it or jumping to the rename feature.

**Comment by derceg** [comment]
I haven't done any testing, so I can't say exactly what the issue would be, but when you create a file via the right click menu, there's a callback that's meant to be executed. That callback places the new item into rename mode. It's possible the relevant shell interface has been changed or updated in Windows 10.

**Comment by derceg** [comment]
It looks like the "new menu" shell extension in Windows 10 passes a `flags` value of `3` to INewMenuClient::SelectAndEditItem. According to the [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378314.aspx), there is no flag with that value.

The reason why Explorer++ never puts the new item into rename mode is that it expects to receive the `NMCSAEI_EDIT` flag (which has a value of `1`). Updating the code so that it puts an item into rename mode whenever `1` or `3` is received appears to work.

**Comment by dutenhnj** [comment]
So either it is a bug in windows 10 itself, or they haven't updated the documentation, interesting.

I noticed another glitch about renaming files that is probably related to this.  If you rename a file, then push Tab to switch to the next file, it selects the next file but fails to go into the editing mode.  But it only happens if you actually rename the first file, if you don't rename it and just hit tab, it opens the next file name for editing as it should.

**Comment by derceg** [comment]
> I noticed another glitch about renaming files that is probably related to this. If you rename a file, then push Tab to switch to the next file, it selects the next file but fails to go into the editing mode. But it only happens if you actually rename the first file, if you don't rename it and just hit tab, it opens the next file name for editing as it should.

Can you create a new issue for this? It looks like the rename should probably be done silently (a progress dialog currently pops up).

**Comment by jat255** [comment]
Found this issue when searching for this problem. I have nothing to contribute to the code, but in the meantime before it's fixed, I created the following AutoHotkey script to workaround the issue, using Ctrl+Shift+N as the shortcut:

```ahk
; Remap new-folder shortcut
#IfWinActive ahk_class Explorer++
^+n::
   Send, ^n{f5}new{f2}
Return
```

**Comment by gustavotrott** [comment]
I didn't undertand if it was fixed or not?

For me it is happening yet, if I create a new folder, it is not selected and not in editing name mode.
Also, if I select the folder I can't delete! I need to select other thing and after that I can select and delete.

Is this in the issues list or I should open other issue?

Using Windows 10 Pro here.
