### ISSUE TITLE
How did you get the correct application icon for each file?

### ISSUE THREAD

**Issue by anik786** [derceg/explorerplusplus#57]
Not really an issue, but rather just a few questions.

Q1) How did you manage to get the correct application icon for each file?
Q2) How did you manage to get the same context menu (when you right click on a file) as the original Windows File Explorer?

**Comment by derceg** [comment]
1. The icon is retrieved using a call to [SHGetFileInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762179(v=vs.85).aspx). See [here](https://github.com/derceg/explorerplusplus/blob/519117aa1fc215c0346bf1918ae8b0924f5e9a96/Explorer%2B%2B/Explorer%2B%2B/SearchDialog.cpp#L974) for an example call.

2. The context menu is retrieved by querying for the [IContextMenu](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776095(v=vs.85).aspx) interface. See [FileContextMenuManager.cpp](https://github.com/derceg/explorerplusplus/blob/519117aa1fc215c0346bf1918ae8b0924f5e9a96/Explorer%2B%2B/Helper/FileContextMenuManager.cpp).

**Comment by anik786** [comment]
Thanks! will have a look
