### ISSUE TITLE
Crash when using display window

### ISSUE THREAD

**Issue by damajor** [derceg/explorerplusplus#59]
I noticed a crash (can be reproduced easily) when you have activated the display window.

Reproduce steps:
- just navigate across a folder with some videos
- use the arrows to move quickly up & down (repeat)
- and crash...

**Comment by kenstuddy** [comment]
I was able to reproduce this crash. I have narrowed it down to K-Lite, at least in my case, and video thumbnail generation. The faulting DLL was swscale-ics-4.dll. I resolved this crash by renaming swscale-ics-4.dll located in C:\Program Files (x86)\K-Lite Codec Pack\Icaros\64-bit to swscale-ics-4.old. However, this gets rid of video thumbnail generation and may not be a suitable solution.
