### ISSUE TITLE
Make compatible with Windows 8.1 DPI Scaling

### ISSUE THREAD

**Issue by patrick-wc** [derceg/explorerplusplus#6]
Hey, I love Explorer++ but I use Windows Scaling set at 175% (my resolution is quite high) and it would be great if the program could adapt itself. The only real bug I have is the Address Bar text isn't readable.

![image](https://f.cloud.github.com/assets/2206382/1975270/720e597e-837b-11e3-80b4-9c7b63116ab9.png)

Thanks for a great piece of software.

**Comment by derceg** [comment]
Duplicate of #150.
