### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by carun** [derceg/explorerplusplus#63]
Hi, it looks like the last release 1.3.5.531 was in Feb 03, 2013.

I see that [lots of bugs have been fixed](https://github.com/derceg/explorerplusplus/compare/version-1.3.5...master) meanwhile. So it might be worth a release.

Is there a plan for a new version?

**Comment by PingNGE** [comment]
Hi, same for me.

I noticed it was not crashing after installation, it began for me after tools like TortoiseSVN/GitExtensions, that affect the contextual menu.

**Comment by endo64** [comment]
Crash problem appeared for me after installed / enabled Microsoft OneDrive synchronization, on two different PC.

**Comment by derceg** [comment]
The bookmarks code is currently in an incomplete state. I had removed the old bookmarks code and started implementing a newer system, however I never got around to finishing it. From memory, that's the main thing holding up any future release.

**Comment by derceg** [comment]
There's no new version just yet, but you can now download updated builds from the [AppVeyor page](https://ci.appveyor.com/project/derceg/explorerplusplus) for this project. That will at least allow you to make use of some of the changes that have been made.

**Comment by derceg** [comment]
For what it's worth, the next version will probably be released soon.

**Comment by carun** [comment]
FWIW, I've found Double Commander to be a best replacement for all the explorer alternatives out there.

https://doublecmd.sourceforge.io/

**Comment by endo64** [comment]
@carun I'm not sure it is polite to advertise another application here.

**Comment by carun** [comment]
@endo64 advertising was not my intent, but given that the app has not been updated since 2013, this gives alternatives to the users. Both are open source and competition (if there's one) is healthy, after all.
