### ISSUE TITLE
Hi, explore++ crash when right click on win10_64 sometimes, not everytime

### ISSUE THREAD

**Issue by nottellyou** [derceg/explorerplusplus#65]
Hi, explore++ crash when right click on win10_64 sometimes, not everytime

**Comment by derceg** [comment]
It sounds like this is a duplicate of #35. If possible, can you try disabling OneDrive and see if that helps?

**Comment by Ashark** [comment]
As for me, it was crashing on win10_64 when right click in empty space everywhere besides root "My computer" folder.
It was not possible to delete C:\Users\username\AppData\Local\Microsoft\OneDrive neither directly (even with admin privilages) nor with `rd "%LocalAppData%\Microsoft\OneDrive" /Q /S` command. It said that files inside were in use by Explorer and permission was denied.
**I booted to Linux, mounted windows partition and removed that folder.** Then booted to windows.
It worked. Explorer++ do not crashes anymore.

**Comment by nguyendangdung** [comment]
Run the app as Administrator then the crash has gone

**Comment by nottellyou** [comment]
Now I remove the OneDrive , it seems working fine.

**Comment by Squelsh** [comment]
Can confirm that. Works when OneDrive is removed.
@Ashark I used the standard deinstallation from the system settings to get rid of OneDrive without hassle.
