### ISSUE TITLE
Crash when closing tabs in details view

### ISSUE THREAD

**Issue by kenstuddy** [derceg/explorerplusplus#68]
Hello,

Sometimes when I close a tab with the default view type set to details, the program crashes. This crash doesn't always happen but if I close multiple tabs rapidly I can replicate it almost 100% of the time - when the default view type is set to medium icons, I can rapidly close many tabs with no crashing whatsoever. This issue happens on the master branch version 1.4.0.79 (x64) as well as version 1.3.5 (x64). I have attached a screenshot of the two errors I get in event viewer. Sometimes I get the first error, other times I get the second error. I am running Windows 10 64-Bit.
![tab crash](https://user-images.githubusercontent.com/24435334/27010664-7b746e3e-4e77-11e7-8384-7a059c8418d8.png)
![tab crash 2](https://user-images.githubusercontent.com/24435334/27010742-9da30658-4e79-11e7-92f5-e88b33e38e6b.png)

Thanks.

**Comment by derceg** [comment]
Do you have Visual Studio set up? If so, are you able to pinpoint the function that it's crashing in? You can do that by debugging it, or by using the crash dump + PDB symbols that are available for the master branch version.

**Comment by kenstuddy** [comment]
I am not able to pinpoint the function it is crashing in, however, here is the call stack:

```
>	ntdll.dll!00007ffd100ebbef()	Unknown
 	ntdll.dll!00007ffd100c4571()	Unknown
 	ntdll.dll!00007ffd100c4490()	Unknown
 	Explorer++.exe!00007ff7621edc29()	Unknown
 	[External Code]	
 	Explorer++.exe!00007ff76218f85e()	Unknown
 	[External Code]	
```
