### ISSUE TITLE
Drag'n'drop is lacking some functionality

### ISSUE THREAD

**Issue by Tallefer** [derceg/explorerplusplus#75]
Dragging and dropping objects on executables and shortcuts (like in common explorer.exe) is not working.

**Comment by jczanfona** [comment]
Exact! Is only allowed to drag and drop to a folder, not to another file.
Is necessary to drag and drop over the files too ZIP BAT ....

**Comment by jczanfona** [comment]
Is still necessary to drag and drop over the files too ZIP BAT ....

**Comment by derceg** [comment]
This should work now (and does work for me in Windows 10). Any target that's valid in Explorer should also be valid in Explorer++.

**Comment by jczanfona** [comment]
Is not possible to move a file over .ZIP file

**Comment by derceg** [comment]
The best thing to do would be to file a new issue with more information.

**Comment by jczanfona** [comment]
ok

**Comment by jczanfona** [comment]
Done in https://github.com/derceg/explorerplusplus/issues/317
