### ISSUE TITLE
Are these bugs ??

### ISSUE THREAD

**Issue by nottellyou** [derceg/explorerplusplus#81]
Hi,
    I  find some bugs on win10_64。

　1）、The translation explorer++ZH.dll　　can't  fit explorer.exe (32)
　2）、The bookmarks can't show in "Bookmarks"  

Regards.

**Comment by derceg** [comment]
Depending on the version of Explorer++ you're using, the translations might not work. The translations linked to in the readme still target version 1.3.5, so they won't work with the development build. I plan on updating them though.

About the bookmarks, it's a known issue. The functionality is in an incomplete state in the development builds.
