### ISSUE TITLE
Request: add customizable hotkeys

### ISSUE THREAD

**Issue by YakovL** [derceg/explorerplusplus#84]
Hi, first of all thanks for your work on Explorer++!

There's a number of nice features that Explorer++ offers but some of them lack hotkey shortcuts (most notably, open cmd) and some shortcuts are quite unfamiliar (like ctrl+T for open in new tab which is expected to always just open a new tab) or even hard to find (ctrl+E for duplicating a tab). So my request is to make this customizable – collect commands, put a table with command-hotkey pairs in options, let user decide. (This will also simplify understanding of what is implemented in E++ and what is not)

Best regards.

**Comment by long-nguyenxuan** [comment]
Looking forward to this feature got implemented, I use `Ctrl-D` to delete files (as in Explorer) but in Explorer++ `Ctrl-D` got bound to `Bookmark`

**Comment by derceg** [comment]
This work is now tracked in #476.
