### ISSUE TITLE
Request: Open programs in the PATH using the address bar

### ISSUE THREAD

**Issue by Slider-Whistle** [derceg/explorerplusplus#86]
This functionality is in windows explorer. It's not crucial, but it could save a couple of clicks in some setups when you want to, for example, run taskkill on a program you've just opened

**Comment by derceg** [comment]
I spent a fair amount of time recently looking at exactly what sort of paths Explorer accepts in the address bar/command line (as part of the work on ea21150210288a05ac40d876de7f69a5136082c9). While Explorer does run applications that are in the PATH, my view is that that functionality has a number of problems.

For example, it creates ambiguity. If you type "cmd", you could be referring to "C:\Windows\System32\cmd.exe", or to a folder named "cmd" in the current directory. Explorer gives precedence to items in the current directory, but I don't think the user intent is clear. If typing "cmd" opens "C:\Windows\System32\cmd.exe" in most cases, then that might be what the user is expecting. Opening items on the PATH sometimes and relative items at other times is inconsistent.

It's also potentially surprising. The user may not even realize they have an executable with a specific name in the PATH. It's also obscure, as it's not something that's easily discoverable, especially when it's inconsistent.

Finally, it makes it harder to perform any actual error checking on the path the user entered. For example, you might have a folder named "cmds" in the current directory. If you accidentally type "cmd" (and there's no item with that name in the current directory), then the application can leave the text in the address bar or show an error. I think, in that context, trying to execute a PATH item is wrong.

Explorer will also open URLs that are entered in the address bar, but that's also likely not something that I'm going to implement, for some of the same reasons as above. For example, if you enter "google.com", then that will be opened in the default browser. But "google.com" is also a valid folder name, so if you have a folder in the current directory with that name, entering "google.com" in the address bar will open the folder, which is inconsistent.

If you do have applications you want to easily open, you could add them to the applications toolbar, or to the bookmarks toolbar. Previously, you could only bookmark folders, but that restriction has been lifted, so you could just bookmark a particular application that you want to open.

**Comment by Slider-Whistle** [comment]
All good with me. At the time I was just wondering whether it was something worth considering, and you put plenty of consideration in there.
