### ISSUE TITLE
Request: Relative Directories

### ISSUE THREAD

**Issue by Slider-Whistle** [derceg/explorerplusplus#87]
It's a little pointless seeing as the backspace key does this faster, but typing the directory ".." in the address bar does nothing

**Comment by derceg** [comment]
As of a recent change (see ea21150210288a05ac40d876de7f69a5136082c9), this should work correctly. The exception being where going up would involve moving from the filesystem to the shell namespace (e.g. going up from C:\\).

**Comment by GoogleBeEvil** [comment]
test on 1.4，still can not do this ，either in cmd line
@derceg
