### ISSUE TITLE
Request: Option to disable double-clicks outside of files making the program go up a directory

### ISSUE THREAD

**Issue by Slider-Whistle** [derceg/explorerplusplus#90]
Sorry, wasn't entirely sure how to describe that feature, but it seems to have been implemented deliberately.  It's probably better than the program doing nothing, but it bugs me a little. Adding onto this, would it be too absurd to ask that, when this option is enabled, that file selection isn't limited by the overall width of the columns? I think some other file browsers worked this way, and I personally found it convenient

**Comment by derceg** [comment]
This was implemented in 9a464994f0fac4e0eb3c5f7348517ec5096f593b.

> Adding onto this, would it be too absurd to ask that, when this option is enabled, that file selection isn't limited by the overall width of the columns?

If you mean that double-clicking anywhere to the right of the last column would open the item on that row, I'm not sure if there's an elegant way of implementing that. Please file a new issue if it's something you'd still like to see, along with some more detail about how it works in other applications.
