### ISSUE TITLE
Request: Option to disable Windows' stupid "root directory" conventions

### ISSUE THREAD

**Issue by Slider-Whistle** [derceg/explorerplusplus#92]
If you go two directories above a lettered drive, you first go to Windows' drive selection directory (what the highest directory SHOULD be, in my opinion), and then, out of nowhere, to %USERPROFILE%\Desktop, which is actually three directories lower. I know that's how windows does it, but that's just fucking stupid.

**Comment by derceg** [comment]
I agree it's odd, but given that's how the namespace is structured, it's simplest just to stick to that. Trying to do something different would add a bunch of complexity.
