### ISSUE TITLE
Explorer++ crashes when accessing OpenAFS (AFSRDRFsd / network) filesystem

### ISSUE THREAD

**Issue by warwebamp** [derceg/explorerplusplus#94]
Explorer++ 64-bit crashes in Windows 10 Pro 64-bit when accessing OpenAFS filesystem, either as a UNC path or mapped network drive.

Explorer++ seems to be able to enumerate the directory contents correctly, but then immediately crashes.

When using native Windows explorer, everything works as expected, so I do not believe this is an OpenAFS issue.

I'm using the latest version of OpenAFS 64-bit (1.7.3301) on which can be downloaded here:

https://www.auristor.com//downloads/openafs/windows/x64/yfs-openafs-en_US-AMD64-1_7_3301.msi

**Comment by derceg** [comment]
I can't reproduce this, so I'll close this for now. If you can reproduce this in the latest version, please provide a crash dump, or more information about the crash (e.g. whether it only happens in something like details view or if it happens when using default settings).
