### ISSUE TITLE
Explorer++ does not obey System.IsPinnedToNamespaceTree for Dropbox

### ISSUE THREAD

**Issue by warwebamp** [derceg/explorerplusplus#95]
I am able to prevent the Dropbox link from showing up in the native Windows explorer navigation pane by following the instructions here (the highlighted "accepted solution):

https://www.dropboxforum.com/t5/Installation-and-desktop-app/How-does-one-remove-the-Dropbox-link-from-the-Navigation-Pane-om/td-p/93970

This solution involves denying the system read permissions on a specific registry key.

This works for the native Windows explorer, but the Dropbox link is still showing up in Explorer++.

Explorer++ should obey user customizations to System.IsPinnedToNamespaceTree.

**Comment by warwebamp** [comment]
I noticed that there are other reserved namespace items that have problems displaying correctly.

For example, when I open my Desktop view, I see three separate entries for the system Control Panel:

1. Control Panel
2. All Control Panel Items
3. ::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}

In the past, I have used UI tweaking programs to control the display of various items in the native Windows explorer, like the Network Neighborhood, individual user libraries, etc.

Explorer++ should obey these customizations, or they should be configurable.

**Comment by derceg** [comment]
Regarding the control panel items mentioned in the second message, I can't find anything that distinguishes them from regular items. That is, I can't find anything like the System.IsPinnedToNamespaceTree property that would result in the items being hidden in the main pane. That means that aside from hiding those specific items manually, I'm not sure how else it would be done.

Also, the third item you listed (::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}) is really just the "Control Panel" item, but Explorer++ wasn't showing the appropriate name (something that's now fixed).

Finally, although Explorer doesn't show the "All Control Panel Items" folder and "Control Panel" item, it still displays the "Control Panel" folder.

Unless you know of a specific property these items have that distinguishes them from other items, they won't be hidden.
